---@class Gruvbox
---@field config GruvboxConfig
---@field palette GruvboxPalette
local Gruvbox = {}

---@alias Contrast "hard" | "soft" | ""

---@class ItalicConfig
---@field strings boolean
---@field comments boolean
---@field operators boolean
---@field folds boolean
---@field emphasis boolean

---@class HighlightDefinition
---@field fg string?
---@field bg string?
---@field sp string?
---@field blend integer?
---@field bold boolean?
---@field standout boolean?
---@field underline boolean?
---@field undercurl boolean?
---@field underdouble boolean?
---@field underdotted boolean?
---@field strikethrough boolean?
---@field italic boolean?
---@field reverse boolean?
---@field nocombine boolean?

---@class GruvboxConfig
---@field terminal_colors boolean?
---@field undercurl boolean?
---@field underline boolean?
---@field bold boolean?
---@field italic ItalicConfig?
---@field strikethrough boolean?
---@field contrast Contrast?
---@field invert_selection boolean?
---@field invert_signs boolean?
---@field invert_tabline boolean?
---@field invert_intend_guides boolean?
---@field inverse boolean?
---@field overrides table<string, HighlightDefinition>?
---@field palette_overrides table<string, string>?
Gruvbox.config = {
  terminal_colors = true,
  undercurl = true,
  underline = true,
  bold = true,
  italic = {
    strings = true,
    emphasis = true,
    comments = true,
    operators = false,
    folds = true,
  },
  strikethrough = true,
  invert_selection = false,
  invert_signs = false,
  invert_tabline = false,
  invert_intend_guides = false,
  inverse = true,
  contrast = "",
  palette_overrides = {},
  overrides = {},
  dim_inactive = false,
  transparent_mode = false,
}

-- main gruvbox color palette
---@class GruvboxPalette
Gruvbox.palette = {
  dark0_hard = "#1d2021",
  dark0 = "#282828",
  dark0_soft = "#32302f",
  dark1 = "#3c3836",
  dark2 = "#504945",
  dark3 = "#665c54",
  dark4 = "#7c6f64",
  light0_hard = "#f9f5d7",
  light0 = "#fbf1c7",
  light0_soft = "#f2e5bc",
  light1 = "#ebdbb2",
  light2 = "#d5c4a1",
  light3 = "#bdae93",
  light4 = "#a89984",
  bright_red = "#fb4934",
  bright_green = "#b8bb26",
  bright_yellow = "#fabd2f",
  bright_blue = "#83a598",
  bright_purple = "#d3869b",
  bright_aqua = "#8ec07c",
  bright_orange = "#fe8019",
  neutral_red = "#cc241d",
  neutral_green = "#98971a",
  neutral_yellow = "#d79921",
  neutral_blue = "#458588",
  neutral_purple = "#b16286",
  neutral_aqua = "#689d6a",
  neutral_orange = "#d65d0e",
  faded_red = "#9d0006",
  faded_green = "#79740e",
  faded_yellow = "#b57614",
  faded_blue = "#076678",
  faded_purple = "#8f3f71",
  faded_aqua = "#427b58",
  faded_orange = "#af3a03",
  dark_red_hard = "#792329",
  dark_red = "#722529",
  dark_red_soft = "#7b2c2f",
  light_red_hard = "#fc9690",
  light_red = "#fc9487",
  light_red_soft = "#f78b7f",
  dark_green_hard = "#5a633a",
  dark_green = "#62693e",
  dark_green_soft = "#686d43",
  light_green_hard = "#d3d6a5",
  light_green = "#d5d39b",
  light_green_soft = "#cecb94",
  dark_aqua_hard = "#3e4934",
  dark_aqua = "#49503b",
  dark_aqua_soft = "#525742",
  light_aqua_hard = "#e6e9c1",
  light_aqua = "#e8e5b5",
  light_aqua_soft = "#e1dbac",
  gray = "#928374",
}

-- get a hex list of gruvbox colors based on current bg and constrast config
local function get_colors()
  local p = Gruvbox.palette
  local config = Gruvbox.config

  for color, hex in pairs(config.palette_overrides) do
    p[color] = hex
  end

  local bg = vim.o.background
  local contrast = config.contrast

  local color_groups = {
    dark = {
      bg0 = p.dark0,
      bg1 = p.dark1,
      bg2 = p.dark2,
      bg3 = p.dark3,
      bg4 = p.dark4,
      fg0 = p.light0,
      fg1 = p.light1,
      fg2 = p.light2,
      fg3 = p.light3,
      fg4 = p.light4,
      red = p.bright_red,
      green = p.bright_green,
      yellow = p.bright_yellow,
      blue = p.bright_blue,
      purple = p.bright_purple,
      aqua = p.bright_aqua,
      orange = p.bright_orange,
      neutral_red = p.neutral_red,
      neutral_green = p.neutral_green,
      neutral_yellow = p.neutral_yellow,
      neutral_blue = p.neutral_blue,
      neutral_purple = p.neutral_purple,
      neutral_aqua = p.neutral_aqua,
      dark_red = p.dark_red,
      dark_green = p.dark_green,
      dark_aqua = p.dark_aqua,
      gray = p.gray,
    },
    light = {
      bg0 = p.light0,
      bg1 = p.light1,
      bg2 = p.light2,
      bg3 = p.light3,
      bg4 = p.light4,
      fg0 = p.dark0,
      fg1 = p.dark1,
      fg2 = p.dark2,
      fg3 = p.dark3,
      fg4 = p.dark4,
      red = p.faded_red,
      green = p.faded_green,
      yellow = p.faded_yellow,
      blue = p.faded_blue,
      purple = p.faded_purple,
      aqua = p.faded_aqua,
      orange = p.faded_orange,
      neutral_red = p.neutral_red,
      neutral_green = p.neutral_green,
      neutral_yellow = p.neutral_yellow,
      neutral_blue = p.neutral_blue,
      neutral_purple = p.neutral_purple,
      neutral_aqua = p.neutral_aqua,
      dark_red = p.light_red,
      dark_green = p.light_green,
      dark_aqua = p.light_aqua,
      gray = p.gray,
    },
  }

  if contrast ~= nil and contrast ~= "" then
    color_groups[bg].bg0 = p[bg .. "0_" .. contrast]
    color_groups[bg].dark_red = p[bg .. "_red_" .. contrast]
    color_groups[bg].dark_green = p[bg .. "_green_" .. contrast]
    color_groups[bg].dark_aqua = p[bg .. "_aqua_" .. contrast]
  end

  return color_groups[bg]
end

local function get_groups()
  local colors = get_colors()
  local config = Gruvbox.config

  if config.terminal_colors then
    local term_colors = {
      colors.bg0,
      colors.neutral_red,
      colors.neutral_green,
      colors.neutral_yellow,
      colors.neutral_blue,
      colors.neutral_purple,
      colors.neutral_aqua,
      colors.fg4,
      colors.gray,
      colors.red,
      colors.green,
      colors.yellow,
      colors.blue,
      colors.purple,
      colors.aqua,
      colors.fg1,
    }
    for index, value in ipairs(term_colors) do
      vim.g["terminal_color_" .. index - 1] = value
    end
  end

  -- local groups = {
  --   GruvboxFg0 = { fg = colors.fg0 },
  --   GruvboxFg1 = { fg = colors.fg1 },
  --   GruvboxFg2 = { fg = colors.fg2 },
  --   GruvboxFg3 = { fg = colors.fg3 },
  --   GruvboxFg4 = { fg = colors.fg4 },
  --   GruvboxGray = { fg = colors.gray },
  --   GruvboxBg0 = { fg = colors.bg0 },
  --   GruvboxBg1 = { fg = colors.bg1 },
  --   GruvboxBg2 = { fg = colors.bg2 },
  --   GruvboxBg3 = { fg = colors.bg3 },
  --   GruvboxBg4 = { fg = colors.bg4 },
  --   GruvboxRed = { fg = colors.red },
  --   GruvboxRedBold = { fg = colors.red, bold = config.bold },
  --   GruvboxGreen = { fg = colors.green },
  --   GruvboxGreenBold = { fg = colors.green, bold = config.bold },
  --   GruvboxYellow = { fg = colors.yellow },
  --   GruvboxYellowBold = { fg = colors.yellow, bold = config.bold },
  --   GruvboxBlue = { fg = colors.blue },
  --   GruvboxBlueBold = { fg = colors.blue, bold = config.bold },
  --   GruvboxPurple = { fg = colors.purple },
  --   GruvboxPurpleBold = { fg = colors.purple, bold = config.bold },
  --   GruvboxAqua = { fg = colors.aqua },
  --   GruvboxAquaBold = { fg = colors.aqua, bold = config.bold },
  --   GruvboxOrange = { fg = colors.orange },
  --   GruvboxOrangeBold = { fg = colors.orange, bold = config.bold },
  --   GruvboxRedSign = config.transparent_mode and { fg = colors.red, reverse = config.invert_signs }
  --     or { fg = colors.red, bg = colors.bg1, reverse = config.invert_signs },
  --   GruvboxGreenSign = config.transparent_mode and { fg = colors.green, reverse = config.invert_signs }
  --     or { fg = colors.green, bg = colors.bg1, reverse = config.invert_signs },
  --   GruvboxYellowSign = config.transparent_mode and { fg = colors.yellow, reverse = config.invert_signs }
  --     or { fg = colors.yellow, bg = colors.bg1, reverse = config.invert_signs },
  --   GruvboxBlueSign = config.transparent_mode and { fg = colors.blue, reverse = config.invert_signs }
  --     or { fg = colors.blue, bg = colors.bg1, reverse = config.invert_signs },
  --   GruvboxPurpleSign = config.transparent_mode and { fg = colors.purple, reverse = config.invert_signs }
  --     or { fg = colors.purple, bg = colors.bg1, reverse = config.invert_signs },
  --   GruvboxAquaSign = config.transparent_mode and { fg = colors.aqua, reverse = config.invert_signs }
  --     or { fg = colors.aqua, bg = colors.bg1, reverse = config.invert_signs },
  --   GruvboxOrangeSign = config.transparent_mode and { fg = colors.orange, reverse = config.invert_signs }
  --     or { fg = colors.orange, bg = colors.bg1, reverse = config.invert_signs },
  --   GruvboxRedUnderline = { undercurl = config.undercurl, sp = colors.red },
  --   GruvboxGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
  --   GruvboxYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
  --   GruvboxBlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
  --   GruvboxPurpleUnderline = { undercurl = config.undercurl, sp = colors.purple },
  --   GruvboxAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
  --   GruvboxOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },
  --   Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
  --   NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
  --   NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
  --   CursorLine = { bg = colors.bg1 },
  --   CursorColumn = { link = "CursorLine" },
  --   TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
  --   TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
  --   TabLine = { link = "TabLineFill" },
  --   MatchParen = { bg = colors.bg3, bold = config.bold },
  --   ColorColumn = { bg = colors.bg1 },
  --   Conceal = { fg = colors.blue },
  --   CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
  --   NonText = { link = "GruvboxBg2" },
  --   SpecialKey = { link = "GruvboxFg4" },
  --   Visual = { bg = colors.bg3, reverse = config.invert_selection },
  --   VisualNOS = { link = "Visual" },
  --   Search = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
  --   IncSearch = { fg = colors.orange, bg = colors.bg0, reverse = config.inverse },
  --   CurSearch = { link = "IncSearch" },
  --   QuickFixLine = { link = "GruvboxPurple" },
  --   Underlined = { fg = colors.blue, underline = config.underline },
  --   StatusLine = { fg = colors.bg2, bg = colors.fg1, reverse = config.inverse },
  --   StatusLineNC = { fg = colors.bg1, bg = colors.fg4, reverse = config.inverse },
  --   WinBar = { fg = colors.fg4, bg = colors.bg0 },
  --   WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
  --   WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil } or { fg = colors.bg3, bg = colors.bg0 },
  --   WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
  --   Directory = { link = "GruvboxBlueBold" },
  --   Title = { link = "GruvboxGreenBold" },
  --   ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
  --   MoreMsg = { link = "GruvboxYellowBold" },
  --   ModeMsg = { link = "GruvboxYellowBold" },
  --   Question = { link = "GruvboxOrangeBold" },
  --   WarningMsg = { link = "GruvboxRedBold" },
  --   LineNr = { fg = colors.bg4 },
  --   SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg1 },
  --   Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic.folds },
  --   FoldColumn = config.transparent_mode and { fg = colors.gray, bg = nil } or { fg = colors.gray, bg = colors.bg1 },
  --   Cursor = { reverse = config.inverse },
  --   vCursor = { link = "Cursor" },
  --   iCursor = { link = "Cursor" },
  --   lCursor = { link = "Cursor" },
  --   Special = { link = "GruvboxOrange" },
  --   Comment = { fg = colors.gray, italic = config.italic.comments },
  --   Todo = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic.comments },
  --   Done = { fg = colors.orange, bold = config.bold, italic = config.italic.comments },
  --   Error = { fg = colors.red, bold = config.bold, reverse = config.inverse },
  --   Statement = { link = "GruvboxRed" },
  --   Conditional = { link = "GruvboxRed" },
  --   Repeat = { link = "GruvboxRed" },
  --   Label = { link = "GruvboxRed" },
  --   Exception = { link = "GruvboxRed" },
  --   Operator = { fg = colors.orange, italic = config.italic.operators },
  --   Keyword = { link = "GruvboxRed" },
  --   Identifier = { link = "GruvboxBlue" },
  --   Function = { link = "GruvboxGreenBold" },
  --   PreProc = { link = "GruvboxAqua" },
  --   Include = { link = "GruvboxAqua" },
  --   Define = { link = "GruvboxAqua" },
  --   Macro = { link = "GruvboxAqua" },
  --   PreCondit = { link = "GruvboxAqua" },
  --   Constant = { link = "GruvboxPurple" },
  --   Character = { link = "GruvboxPurple" },
  --   String = { fg = colors.green, italic = config.italic.strings },
  --   Boolean = { link = "GruvboxPurple" },
  --   Number = { link = "GruvboxPurple" },
  --   Float = { link = "GruvboxPurple" },
  --   Type = { link = "GruvboxYellow" },
  --   StorageClass = { link = "GruvboxOrange" },
  --   Structure = { link = "GruvboxAqua" },
  --   Typedef = { link = "GruvboxYellow" },
  --   Pmenu = { fg = colors.fg1, bg = colors.bg2 },
  --   PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
  --   PmenuSbar = { bg = colors.bg2 },
  --   PmenuThumb = { bg = colors.bg4 },
  --   DiffDelete = { bg = colors.dark_red },
  --   DiffAdd = { bg = colors.dark_green },
  --   DiffChange = { bg = colors.dark_aqua },
  --   DiffText = { bg = colors.yellow, fg = colors.bg0 },
  --   SpellCap = { link = "GruvboxBlueUnderline" },
  --   SpellBad = { link = "GruvboxRedUnderline" },
  --   SpellLocal = { link = "GruvboxAquaUnderline" },
  --   SpellRare = { link = "GruvboxPurpleUnderline" },
  --   Whitespace = { fg = colors.bg2 },
  --   DiagnosticError = { link = "GruvboxRed" },
  --   DiagnosticSignError = { link = "GruvboxRedSign" },
  --   DiagnosticUnderlineError = { link = "GruvboxRedUnderline" },
  --   DiagnosticWarn = { link = "GruvboxYellow" },
  --   DiagnosticSignWarn = { link = "GruvboxYellowSign" },
  --   DiagnosticUnderlineWarn = { link = "GruvboxYellowUnderline" },
  --   DiagnosticInfo = { link = "GruvboxBlue" },
  --   DiagnosticSignInfo = { link = "GruvboxBlueSign" },
  --   DiagnosticUnderlineInfo = { link = "GruvboxBlueUnderline" },
  --   DiagnosticHint = { link = "GruvboxAqua" },
  --   DiagnosticSignHint = { link = "GruvboxAquaSign" },
  --   DiagnosticUnderlineHint = { link = "GruvboxAquaUnderline" },
  --   DiagnosticFloatingError = { link = "GruvboxRed" },
  --   DiagnosticFloatingWarn = { link = "GruvboxOrange" },
  --   DiagnosticFloatingInfo = { link = "GruvboxBlue" },
  --   DiagnosticFloatingHint = { link = "GruvboxAqua" },
  --   DiagnosticVirtualTextError = { link = "GruvboxRed" },
  --   DiagnosticVirtualTextWarn = { link = "GruvboxYellow" },
  --   DiagnosticVirtualTextInfo = { link = "GruvboxBlue" },
  --   DiagnosticVirtualTextHint = { link = "GruvboxAqua" },
  --   DiagnosticOk = { link = "GruvboxGreenSign" },
  --   LspReferenceRead = { link = "GruvboxYellowBold" },
  --   LspReferenceText = { link = "GruvboxYellowBold" },
  --   LspReferenceWrite = { link = "GruvboxOrangeBold" },
  --   LspCodeLens = { link = "GruvboxGray" },
  --   LspSignatureActiveParameter = { link = "Search" },
  --   gitcommitSelectedFile = { link = "GruvboxGreen" },
  --   gitcommitDiscardedFile = { link = "GruvboxRed" },
  --   GitSignsAdd = { link = "GruvboxGreen" },
  --   GitSignsChange = { link = "GruvboxAqua" },
  --   GitSignsDelete = { link = "GruvboxRed" },
  --   NvimTreeSymlink = { fg = colors.neutral_aqua },
  --   NvimTreeRootFolder = { fg = colors.neutral_purple, bold = true },
  --   NvimTreeFolderIcon = { fg = colors.neutral_blue, bold = true },
  --   NvimTreeFileIcon = { fg = colors.light2 },
  --   NvimTreeExecFile = { fg = colors.neutral_green, bold = true },
  --   NvimTreeOpenedFile = { fg = colors.bright_red, bold = true },
  --   NvimTreeSpecialFile = { fg = colors.neutral_yellow, bold = true, underline = true },
  --   NvimTreeImageFile = { fg = colors.neutral_purple },
  --   NvimTreeIndentMarker = { fg = colors.dark3 },
  --   NvimTreeGitDirty = { fg = colors.neutral_yellow },
  --   NvimTreeGitStaged = { fg = colors.neutral_yellow },
  --   NvimTreeGitMerge = { fg = colors.neutral_purple },
  --   NvimTreeGitRenamed = { fg = colors.neutral_purple },
  --   NvimTreeGitNew = { fg = colors.neutral_yellow },
  --   NvimTreeGitDeleted = { fg = colors.neutral_red },
  --   NvimTreeWindowPicker = { bg = colors.aqua },
  --   debugPC = { link = "DiffAdd" },
  --   debugBreakpoint = { link = "GruvboxRedSign" },
  --   StartifyBracket = { link = "GruvboxFg3" },
  --   StartifyFile = { link = "GruvboxFg1" },
  --   StartifyNumber = { link = "GruvboxBlue" },
  --   StartifyPath = { link = "GruvboxGray" },
  --   StartifySlash = { link = "GruvboxGray" },
  --   StartifySection = { link = "GruvboxYellow" },
  --   StartifySpecial = { link = "GruvboxBg2" },
  --   StartifyHeader = { link = "GruvboxOrange" },
  --   StartifyFooter = { link = "GruvboxBg2" },
  --   StartifyVar = { link = "StartifyPath" },
  --   StartifySelect = { link = "Title" },
  --   DirvishPathTail = { link = "GruvboxAqua" },
  --   DirvishArg = { link = "GruvboxYellow" },
  --   netrwDir = { link = "GruvboxAqua" },
  --   netrwClassify = { link = "GruvboxAqua" },
  --   netrwLink = { link = "GruvboxGray" },
  --   netrwSymLink = { link = "GruvboxFg1" },
  --   netrwExe = { link = "GruvboxYellow" },
  --   netrwComment = { link = "GruvboxGray" },
  --   netrwList = { link = "GruvboxBlue" },
  --   netrwHelpCmd = { link = "GruvboxAqua" },
  --   netrwCmdSep = { link = "GruvboxFg3" },
  --   netrwVersion = { link = "GruvboxGreen" },
  --   NERDTreeDir = { link = "GruvboxAqua" },
  --   NERDTreeDirSlash = { link = "GruvboxAqua" },
  --   NERDTreeOpenable = { link = "GruvboxOrange" },
  --   NERDTreeClosable = { link = "GruvboxOrange" },
  --   NERDTreeFile = { link = "GruvboxFg1" },
  --   NERDTreeExecFile = { link = "GruvboxYellow" },
  --   NERDTreeUp = { link = "GruvboxGray" },
  --   NERDTreeCWD = { link = "GruvboxGreen" },
  --   NERDTreeHelp = { link = "GruvboxFg1" },
  --   NERDTreeToggleOn = { link = "GruvboxGreen" },
  --   NERDTreeToggleOff = { link = "GruvboxRed" },
  --   CocErrorSign = { link = "GruvboxRedSign" },
  --   CocWarningSign = { link = "GruvboxOrangeSign" },
  --   CocInfoSign = { link = "GruvboxBlueSign" },
  --   CocHintSign = { link = "GruvboxAquaSign" },
  --   CocErrorFloat = { link = "GruvboxRed" },
  --   CocWarningFloat = { link = "GruvboxOrange" },
  --   CocInfoFloat = { link = "GruvboxBlue" },
  --   CocHintFloat = { link = "GruvboxAqua" },
  --   CocDiagnosticsError = { link = "GruvboxRed" },
  --   CocDiagnosticsWarning = { link = "GruvboxOrange" },
  --   CocDiagnosticsInfo = { link = "GruvboxBlue" },
  --   CocDiagnosticsHint = { link = "GruvboxAqua" },
  --   CocSelectedText = { link = "GruvboxRed" },
  --   CocMenuSel = { link = "PmenuSel" },
  --   CocCodeLens = { link = "GruvboxGray" },
  --   CocErrorHighlight = { link = "GruvboxRedUnderline" },
  --   CocWarningHighlight = { link = "GruvboxOrangeUnderline" },
  --   CocInfoHighlight = { link = "GruvboxBlueUnderline" },
  --   CocHintHighlight = { link = "GruvboxAquaUnderline" },
  --   TelescopeNormal = { link = "GruvboxFg1" },
  --   TelescopeSelection = { link = "GruvboxOrangeBold" },
  --   TelescopeSelectionCaret = { link = "GruvboxRed" },
  --   TelescopeMultiSelection = { link = "GruvboxGray" },
  --   TelescopeBorder = { link = "TelescopeNormal" },
  --   TelescopePromptBorder = { link = "TelescopeNormal" },
  --   TelescopeResultsBorder = { link = "TelescopeNormal" },
  --   TelescopePreviewBorder = { link = "TelescopeNormal" },
  --   TelescopeMatching = { link = "GruvboxBlue" },
  --   TelescopePromptPrefix = { link = "GruvboxRed" },
  --   TelescopePrompt = { link = "TelescopeNormal" },
  --   CmpItemAbbr = { link = "GruvboxFg0" },
  --   CmpItemAbbrDeprecated = { link = "GruvboxFg1" },
  --   CmpItemAbbrMatch = { link = "GruvboxBlueBold" },
  --   CmpItemAbbrMatchFuzzy = { link = "GruvboxBlueUnderline" },
  --   CmpItemMenu = { link = "GruvboxGray" },
  --   CmpItemKindText = { link = "GruvboxOrange" },
  --   CmpItemKindVariable = { link = "GruvboxOrange" },
  --   CmpItemKindMethod = { link = "GruvboxBlue" },
  --   CmpItemKindFunction = { link = "GruvboxBlue" },
  --   CmpItemKindConstructor = { link = "GruvboxYellow" },
  --   CmpItemKindUnit = { link = "GruvboxBlue" },
  --   CmpItemKindField = { link = "GruvboxBlue" },
  --   CmpItemKindClass = { link = "GruvboxYellow" },
  --   CmpItemKindInterface = { link = "GruvboxYellow" },
  --   CmpItemKindModule = { link = "GruvboxBlue" },
  --   CmpItemKindProperty = { link = "GruvboxBlue" },
  --   CmpItemKindValue = { link = "GruvboxOrange" },
  --   CmpItemKindEnum = { link = "GruvboxYellow" },
  --   CmpItemKindOperator = { link = "GruvboxYellow" },
  --   CmpItemKindKeyword = { link = "GruvboxPurple" },
  --   CmpItemKindEvent = { link = "GruvboxPurple" },
  --   CmpItemKindReference = { link = "GruvboxPurple" },
  --   CmpItemKindColor = { link = "GruvboxPurple" },
  --   CmpItemKindSnippet = { link = "GruvboxGreen" },
  --   CmpItemKindFile = { link = "GruvboxBlue" },
  --   CmpItemKindFolder = { link = "GruvboxBlue" },
  --   CmpItemKindEnumMember = { link = "GruvboxAqua" },
  --   CmpItemKindConstant = { link = "GruvboxOrange" },
  --   CmpItemKindStruct = { link = "GruvboxYellow" },
  --   CmpItemKindTypeParameter = { link = "GruvboxYellow" },
  --   diffAdded = { link = "DiffAdd" },
  --   diffRemoved = { link = "DiffDelete" },
  --   diffChanged = { link = "DiffChange" },
  --   diffFile = { link = "GruvboxOrange" },
  --   diffNewFile = { link = "GruvboxYellow" },
  --   diffOldFile = { link = "GruvboxOrange" },
  --   diffLine = { link = "GruvboxBlue" },
  --   diffIndexLine = { link = "diffChanged" },
  --   NavicIconsFile = { link = "GruvboxBlue" },
  --   NavicIconsModule = { link = "GruvboxOrange" },
  --   NavicIconsNamespace = { link = "GruvboxBlue" },
  --   NavicIconsPackage = { link = "GruvboxAqua" },
  --   NavicIconsClass = { link = "GruvboxYellow" },
  --   NavicIconsMethod = { link = "GruvboxBlue" },
  --   NavicIconsProperty = { link = "GruvboxAqua" },
  --   NavicIconsField = { link = "GruvboxPurple" },
  --   NavicIconsConstructor = { link = "GruvboxBlue" },
  --   NavicIconsEnum = { link = "GruvboxPurple" },
  --   NavicIconsInterface = { link = "GruvboxGreen" },
  --   NavicIconsFunction = { link = "GruvboxBlue" },
  --   NavicIconsVariable = { link = "GruvboxPurple" },
  --   NavicIconsConstant = { link = "GruvboxOrange" },
  --   NavicIconsString = { link = "GruvboxGreen" },
  --   NavicIconsNumber = { link = "GruvboxOrange" },
  --   NavicIconsBoolean = { link = "GruvboxOrange" },
  --   NavicIconsArray = { link = "GruvboxOrange" },
  --   NavicIconsObject = { link = "GruvboxOrange" },
  --   NavicIconsKey = { link = "GruvboxAqua" },
  --   NavicIconsNull = { link = "GruvboxOrange" },
  --   NavicIconsEnumMember = { link = "GruvboxYellow" },
  --   NavicIconsStruct = { link = "GruvboxPurple" },
  --   NavicIconsEvent = { link = "GruvboxYellow" },
  --   NavicIconsOperator = { link = "GruvboxRed" },
  --   NavicIconsTypeParameter = { link = "GruvboxRed" },
  --   NavicText = { link = "GruvboxWhite" },
  --   NavicSeparator = { link = "GruvboxWhite" },
  --   htmlTag = { link = "GruvboxAquaBold" },
  --   htmlEndTag = { link = "GruvboxAquaBold" },
  --   htmlTagName = { link = "GruvboxBlue" },
  --   htmlArg = { link = "GruvboxOrange" },
  --   htmlTagN = { link = "GruvboxFg1" },
  --   htmlSpecialTagName = { link = "GruvboxBlue" },
  --   htmlLink = { fg = colors.fg4, underline = config.underline },
  --   htmlSpecialChar = { link = "GruvboxRed" },
  --   htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
  --   htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
  --   htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true },
  --   htmlBoldUnderlineItalic = {
  --     fg = colors.fg0,
  --     bg = colors.bg0,
  --     bold = config.bold,
  --     italic = true,
  --     underline = config.underline,
  --   },
  --   htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
  --   htmlUnderlineItalic = {
  --     fg = colors.fg0,
  --     bg = colors.bg0,
  --     italic = true,
  --     underline = config.underline,
  --   },
  --   htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
  --   xmlTag = { link = "GruvboxAquaBold" },
  --   xmlEndTag = { link = "GruvboxAquaBold" },
  --   xmlTagName = { link = "GruvboxBlue" },
  --   xmlEqual = { link = "GruvboxBlue" },
  --   docbkKeyword = { link = "GruvboxAquaBold" },
  --   xmlDocTypeDecl = { link = "GruvboxGray" },
  --   xmlDocTypeKeyword = { link = "GruvboxPurple" },
  --   xmlCdataStart = { link = "GruvboxGray" },
  --   xmlCdataCdata = { link = "GruvboxPurple" },
  --   dtdFunction = { link = "GruvboxGray" },
  --   dtdTagName = { link = "GruvboxPurple" },
  --   xmlAttrib = { link = "GruvboxOrange" },
  --   xmlProcessingDelim = { link = "GruvboxGray" },
  --   dtdParamEntityPunct = { link = "GruvboxGray" },
  --   dtdParamEntityDPunct = { link = "GruvboxGray" },
  --   xmlAttribPunct = { link = "GruvboxGray" },
  --   xmlEntity = { link = "GruvboxRed" },
  --   xmlEntityPunct = { link = "GruvboxRed" },
  --   clojureKeyword = { link = "GruvboxBlue" },
  --   clojureCond = { link = "GruvboxOrange" },
  --   clojureSpecial = { link = "GruvboxOrange" },
  --   clojureDefine = { link = "GruvboxOrange" },
  --   clojureFunc = { link = "GruvboxYellow" },
  --   clojureRepeat = { link = "GruvboxYellow" },
  --   clojureCharacter = { link = "GruvboxAqua" },
  --   clojureStringEscape = { link = "GruvboxAqua" },
  --   clojureException = { link = "GruvboxRed" },
  --   clojureRegexp = { link = "GruvboxAqua" },
  --   clojureRegexpEscape = { link = "GruvboxAqua" },
  --   clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
  --   clojureRegexpMod = { link = "clojureRegexpCharClass" },
  --   clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
  --   clojureParen = { link = "GruvboxFg3" },
  --   clojureAnonArg = { link = "GruvboxYellow" },
  --   clojureVariable = { link = "GruvboxBlue" },
  --   clojureMacro = { link = "GruvboxOrange" },
  --   clojureMeta = { link = "GruvboxYellow" },
  --   clojureDeref = { link = "GruvboxYellow" },
  --   clojureQuote = { link = "GruvboxYellow" },
  --   clojureUnquote = { link = "GruvboxYellow" },
  --   cOperator = { link = "GruvboxPurple" },
  --   cppOperator = { link = "GruvboxPurple" },
  --   cStructure = { link = "GruvboxOrange" },
  --   pythonBuiltin = { link = "GruvboxOrange" },
  --   pythonBuiltinObj = { link = "GruvboxOrange" },
  --   pythonBuiltinFunc = { link = "GruvboxOrange" },
  --   pythonFunction = { link = "GruvboxAqua" },
  --   pythonDecorator = { link = "GruvboxRed" },
  --   pythonInclude = { link = "GruvboxBlue" },
  --   pythonImport = { link = "GruvboxBlue" },
  --   pythonRun = { link = "GruvboxBlue" },
  --   pythonCoding = { link = "GruvboxBlue" },
  --   pythonOperator = { link = "GruvboxRed" },
  --   pythonException = { link = "GruvboxRed" },
  --   pythonExceptions = { link = "GruvboxPurple" },
  --   pythonBoolean = { link = "GruvboxPurple" },
  --   pythonDot = { link = "GruvboxFg3" },
  --   pythonConditional = { link = "GruvboxRed" },
  --   pythonRepeat = { link = "GruvboxRed" },
  --   pythonDottedName = { link = "GruvboxGreenBold" },
  --   cssBraces = { link = "GruvboxBlue" },
  --   cssFunctionName = { link = "GruvboxYellow" },
  --   cssIdentifier = { link = "GruvboxOrange" },
  --   cssClassName = { link = "GruvboxGreen" },
  --   cssColor = { link = "GruvboxBlue" },
  --   cssSelectorOp = { link = "GruvboxBlue" },
  --   cssSelectorOp2 = { link = "GruvboxBlue" },
  --   cssImportant = { link = "GruvboxGreen" },
  --   cssVendor = { link = "GruvboxFg1" },
  --   cssTextProp = { link = "GruvboxAqua" },
  --   cssAnimationProp = { link = "GruvboxAqua" },
  --   cssUIProp = { link = "GruvboxYellow" },
  --   cssTransformProp = { link = "GruvboxAqua" },
  --   cssTransitionProp = { link = "GruvboxAqua" },
  --   cssPrintProp = { link = "GruvboxAqua" },
  --   cssPositioningProp = { link = "GruvboxYellow" },
  --   cssBoxProp = { link = "GruvboxAqua" },
  --   cssFontDescriptorProp = { link = "GruvboxAqua" },
  --   cssFlexibleBoxProp = { link = "GruvboxAqua" },
  --   cssBorderOutlineProp = { link = "GruvboxAqua" },
  --   cssBackgroundProp = { link = "GruvboxAqua" },
  --   cssMarginProp = { link = "GruvboxAqua" },
  --   cssListProp = { link = "GruvboxAqua" },
  --   cssTableProp = { link = "GruvboxAqua" },
  --   cssFontProp = { link = "GruvboxAqua" },
  --   cssPaddingProp = { link = "GruvboxAqua" },
  --   cssDimensionProp = { link = "GruvboxAqua" },
  --   cssRenderProp = { link = "GruvboxAqua" },
  --   cssColorProp = { link = "GruvboxAqua" },
  --   cssGeneratedContentProp = { link = "GruvboxAqua" },
  --   javaScriptBraces = { link = "GruvboxFg1" },
  --   javaScriptFunction = { link = "GruvboxAqua" },
  --   javaScriptIdentifier = { link = "GruvboxRed" },
  --   javaScriptMember = { link = "GruvboxBlue" },
  --   javaScriptNumber = { link = "GruvboxPurple" },
  --   javaScriptNull = { link = "GruvboxPurple" },
  --   javaScriptParens = { link = "GruvboxFg3" },
  --   typescriptReserved = { link = "GruvboxAqua" },
  --   typescriptLabel = { link = "GruvboxAqua" },
  --   typescriptFuncKeyword = { link = "GruvboxAqua" },
  --   typescriptIdentifier = { link = "GruvboxOrange" },
  --   typescriptBraces = { link = "GruvboxFg1" },
  --   typescriptEndColons = { link = "GruvboxFg1" },
  --   typescriptDOMObjects = { link = "GruvboxFg1" },
  --   typescriptAjaxMethods = { link = "GruvboxFg1" },
  --   typescriptLogicSymbols = { link = "GruvboxFg1" },
  --   typescriptDocSeeTag = { link = "Comment" },
  --   typescriptDocParam = { link = "Comment" },
  --   typescriptDocTags = { link = "vimCommentTitle" },
  --   typescriptGlobalObjects = { link = "GruvboxFg1" },
  --   typescriptParens = { link = "GruvboxFg3" },
  --   typescriptOpSymbols = { link = "GruvboxFg3" },
  --   typescriptHtmlElemProperties = { link = "GruvboxFg1" },
  --   typescriptNull = { link = "GruvboxPurple" },
  --   typescriptInterpolationDelimiter = { link = "GruvboxAqua" },
  --   purescriptModuleKeyword = { link = "GruvboxAqua" },
  --   purescriptModuleName = { link = "GruvboxFg1" },
  --   purescriptWhere = { link = "GruvboxAqua" },
  --   purescriptDelimiter = { link = "GruvboxFg4" },
  --   purescriptType = { link = "GruvboxFg1" },
  --   purescriptImportKeyword = { link = "GruvboxAqua" },
  --   purescriptHidingKeyword = { link = "GruvboxAqua" },
  --   purescriptAsKeyword = { link = "GruvboxAqua" },
  --   purescriptStructure = { link = "GruvboxAqua" },
  --   purescriptOperator = { link = "GruvboxBlue" },
  --   purescriptTypeVar = { link = "GruvboxFg1" },
  --   purescriptConstructor = { link = "GruvboxFg1" },
  --   purescriptFunction = { link = "GruvboxFg1" },
  --   purescriptConditional = { link = "GruvboxOrange" },
  --   purescriptBacktick = { link = "GruvboxOrange" },
  --   coffeeExtendedOp = { link = "GruvboxFg3" },
  --   coffeeSpecialOp = { link = "GruvboxFg3" },
  --   coffeeCurly = { link = "GruvboxOrange" },
  --   coffeeParen = { link = "GruvboxFg3" },
  --   coffeeBracket = { link = "GruvboxOrange" },
  --   rubyStringDelimiter = { link = "GruvboxGreen" },
  --   rubyInterpolationDelimiter = { link = "GruvboxAqua" },
  --   rubyDefinedOperator = { link = "rubyKeyword" },
  --   objcTypeModifier = { link = "GruvboxRed" },
  --   objcDirective = { link = "GruvboxBlue" },
  --   goDirective = { link = "GruvboxAqua" },
  --   goConstants = { link = "GruvboxPurple" },
  --   goDeclaration = { link = "GruvboxRed" },
  --   goDeclType = { link = "GruvboxBlue" },
  --   goBuiltins = { link = "GruvboxOrange" },
  --   luaIn = { link = "GruvboxRed" },
  --   luaFunction = { link = "GruvboxAqua" },
  --   luaTable = { link = "GruvboxOrange" },
  --   moonSpecialOp = { link = "GruvboxFg3" },
  --   moonExtendedOp = { link = "GruvboxFg3" },
  --   moonFunction = { link = "GruvboxFg3" },
  --   moonObject = { link = "GruvboxYellow" },
  --   javaAnnotation = { link = "GruvboxBlue" },
  --   javaDocTags = { link = "GruvboxAqua" },
  --   javaCommentTitle = { link = "vimCommentTitle" },
  --   javaParen = { link = "GruvboxFg3" },
  --   javaParen1 = { link = "GruvboxFg3" },
  --   javaParen2 = { link = "GruvboxFg3" },
  --   javaParen3 = { link = "GruvboxFg3" },
  --   javaParen4 = { link = "GruvboxFg3" },
  --   javaParen5 = { link = "GruvboxFg3" },
  --   javaOperator = { link = "GruvboxOrange" },
  --   javaVarArg = { link = "GruvboxGreen" },
  --   elixirDocString = { link = "Comment" },
  --   elixirStringDelimiter = { link = "GruvboxGreen" },
  --   elixirInterpolationDelimiter = { link = "GruvboxAqua" },
  --   elixirModuleDeclaration = { link = "GruvboxYellow" },
  --   scalaNameDefinition = { link = "GruvboxFg1" },
  --   scalaCaseFollowing = { link = "GruvboxFg1" },
  --   scalaCapitalWord = { link = "GruvboxFg1" },
  --   scalaTypeExtension = { link = "GruvboxFg1" },
  --   scalaKeyword = { link = "GruvboxRed" },
  --   scalaKeywordModifier = { link = "GruvboxRed" },
  --   scalaSpecial = { link = "GruvboxAqua" },
  --   scalaOperator = { link = "GruvboxFg1" },
  --   scalaTypeDeclaration = { link = "GruvboxYellow" },
  --   scalaTypeTypePostDeclaration = { link = "GruvboxYellow" },
  --   scalaInstanceDeclaration = { link = "GruvboxFg1" },
  --   scalaInterpolation = { link = "GruvboxAqua" },
  --   markdownItalic = { fg = colors.fg3, italic = true },
  --   markdownBold = { fg = colors.fg3, bold = config.bold },
  --   markdownBoldItalic = { fg = colors.fg3, bold = config.bold, italic = true },
  --   markdownH1 = { link = "GruvboxGreenBold" },
  --   markdownH2 = { link = "GruvboxGreenBold" },
  --   markdownH3 = { link = "GruvboxYellowBold" },
  --   markdownH4 = { link = "GruvboxYellowBold" },
  --   markdownH5 = { link = "GruvboxYellow" },
  --   markdownH6 = { link = "GruvboxYellow" },
  --   markdownCode = { link = "GruvboxAqua" },
  --   markdownCodeBlock = { link = "GruvboxAqua" },
  --   markdownCodeDelimiter = { link = "GruvboxAqua" },
  --   markdownBlockquote = { link = "GruvboxGray" },
  --   markdownListMarker = { link = "GruvboxGray" },
  --   markdownOrderedListMarker = { link = "GruvboxGray" },
  --   markdownRule = { link = "GruvboxGray" },
  --   markdownHeadingRule = { link = "GruvboxGray" },
  --   markdownUrlDelimiter = { link = "GruvboxFg3" },
  --   markdownLinkDelimiter = { link = "GruvboxFg3" },
  --   markdownLinkTextDelimiter = { link = "GruvboxFg3" },
  --   markdownHeadingDelimiter = { link = "GruvboxOrange" },
  --   markdownUrl = { link = "GruvboxPurple" },
  --   markdownUrlTitleDelimiter = { link = "GruvboxGreen" },
  --   markdownLinkText = { fg = colors.gray, underline = config.underline },
  --   markdownIdDeclaration = { link = "markdownLinkText" },
  --   haskellType = { link = "GruvboxBlue" },
  --   haskellIdentifier = { link = "GruvboxAqua" },
  --   haskellSeparator = { link = "GruvboxFg4" },
  --   haskellDelimiter = { link = "GruvboxOrange" },
  --   haskellOperators = { link = "GruvboxPurple" },
  --   haskellBacktick = { link = "GruvboxOrange" },
  --   haskellStatement = { link = "GruvboxPurple" },
  --   haskellConditional = { link = "GruvboxPurple" },
  --   haskellLet = { link = "GruvboxRed" },
  --   haskellDefault = { link = "GruvboxRed" },
  --   haskellWhere = { link = "GruvboxRed" },
  --   haskellBottom = { link = "GruvboxRedBold" },
  --   haskellImportKeywords = { link = "GruvboxPurpleBold" },
  --   haskellDeclKeyword = { link = "GruvboxOrange" },
  --   haskellDecl = { link = "GruvboxOrange" },
  --   haskellDeriving = { link = "GruvboxPurple" },
  --   haskellAssocType = { link = "GruvboxAqua" },
  --   haskellNumber = { link = "GruvboxAqua" },
  --   haskellPragma = { link = "GruvboxRedBold" },
  --   haskellTH = { link = "GruvboxAquaBold" },
  --   haskellForeignKeywords = { link = "GruvboxGreen" },
  --   haskellKeyword = { link = "GruvboxRed" },
  --   haskellFloat = { link = "GruvboxAqua" },
  --   haskellInfix = { link = "GruvboxPurple" },
  --   haskellQuote = { link = "GruvboxGreenBold" },
  --   haskellShebang = { link = "GruvboxYellowBold" },
  --   haskellLiquid = { link = "GruvboxPurpleBold" },
  --   haskellQuasiQuoted = { link = "GruvboxBlueBold" },
  --   haskellRecursiveDo = { link = "GruvboxPurple" },
  --   haskellQuotedType = { link = "GruvboxRed" },
  --   haskellPreProc = { link = "GruvboxFg4" },
  --   haskellTypeRoles = { link = "GruvboxRedBold" },
  --   haskellTypeForall = { link = "GruvboxRed" },
  --   haskellPatternKeyword = { link = "GruvboxBlue" },
  --   jsonKeyword = { link = "GruvboxGreen" },
  --   jsonQuote = { link = "GruvboxGreen" },
  --   jsonBraces = { link = "GruvboxFg1" },
  --   jsonString = { link = "GruvboxFg1" },
  --   mailQuoted1 = { link = "GruvboxAqua" },
  --   mailQuoted2 = { link = "GruvboxPurple" },
  --   mailQuoted3 = { link = "GruvboxYellow" },
  --   mailQuoted4 = { link = "GruvboxGreen" },
  --   mailQuoted5 = { link = "GruvboxRed" },
  --   mailQuoted6 = { link = "GruvboxOrange" },
  --   mailSignature = { link = "Comment" },
  --   csBraces = { link = "GruvboxFg1" },
  --   csEndColon = { link = "GruvboxFg1" },
  --   csLogicSymbols = { link = "GruvboxFg1" },
  --   csParens = { link = "GruvboxFg3" },
  --   csOpSymbols = { link = "GruvboxFg3" },
  --   csInterpolationDelimiter = { link = "GruvboxFg3" },
  --   csInterpolationAlignDel = { link = "GruvboxAquaBold" },
  --   csInterpolationFormat = { link = "GruvboxAqua" },
  --   csInterpolationFormatDel = { link = "GruvboxAquaBold" },
  --   rustSigil = { link = "GruvboxOrange" },
  --   rustEscape = { link = "GruvboxAqua" },
  --   rustStringContinuation = { link = "GruvboxAqua" },
  --   rustEnum = { link = "GruvboxAqua" },
  --   rustStructure = { link = "GruvboxAqua" },
  --   rustModPathSep = { link = "GruvboxFg2" },
  --   rustCommentLineDoc = { link = "Comment" },
  --   rustDefault = { link = "GruvboxAqua" },
  --   ocamlOperator = { link = "GruvboxFg1" },
  --   ocamlKeyChar = { link = "GruvboxOrange" },
  --   ocamlArrow = { link = "GruvboxOrange" },
  --   ocamlInfixOpKeyword = { link = "GruvboxRed" },
  --   ocamlConstructor = { link = "GruvboxOrange" },
  --   LspSagaCodeActionTitle = { link = "Title" },
  --   LspSagaCodeActionBorder = { link = "GruvboxFg1" },
  --   LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
  --   LspSagaLspFinderBorder = { link = "GruvboxFg1" },
  --   LspSagaAutoPreview = { link = "GruvboxOrange" },
  --   TargetWord = { fg = colors.blue, bold = config.bold },
  --   FinderSeparator = { link = "GruvboxAqua" },
  --   LspSagaDefPreviewBorder = { link = "GruvboxBlue" },
  --   LspSagaHoverBorder = { link = "GruvboxOrange" },
  --   LspSagaRenameBorder = { link = "GruvboxBlue" },
  --   LspSagaDiagnosticSource = { link = "GruvboxOrange" },
  --   LspSagaDiagnosticBorder = { link = "GruvboxPurple" },
  --   LspSagaDiagnosticHeader = { link = "GruvboxGreen" },
  --   LspSagaSignatureHelpBorder = { link = "GruvboxGreen" },
  --   SagaShadow = { link = "GruvboxBg0" },
  --   DashboardShortCut = { link = "GruvboxOrange" },
  --   DashboardHeader = { link = "GruvboxAqua" },
  --   DashboardCenter = { link = "GruvboxYellow" },
  --   DashboardFooter = { fg = colors.purple, italic = true },
  --   MasonHighlight = { link = "GruvboxAqua" },
  --   MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
  --   MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue, bold = true },
  --   MasonHighlightSecondary = { fg = colors.yellow },
  --   MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
  --   MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
  --   MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
  --   MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
  --   MasonMuted = { fg = colors.fg4 },
  --   MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
  --   MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },
  --   LspInlayHint = { link = "comment" },
  --   CarbonFile = { link = "GruvboxFg1" },
  --   CarbonExe = { link = "GruvboxYellow" },
  --   CarbonSymlink = { link = "GruvboxAqua" },
  --   CarbonBrokenSymlink = { link = "GruvboxRed" },
  --   CarbonIndicator = { link = "GruvboxGray" },
  --   CarbonDanger = { link = "GruvboxRed" },
  --   CarbonPending = { link = "GruvboxYellow" },
  --   NoiceCursor = { link = "TermCursor" },
  --   NotifyDEBUGBorder = { link = "GruvboxBlue" },
  --   NotifyDEBUGIcon = { link = "GruvboxBlue" },
  --   NotifyDEBUGTitle = { link = "GruvboxBlue" },
  --   NotifyERRORBorder = { link = "GruvboxRed" },
  --   NotifyERRORIcon = { link = "GruvboxRed" },
  --   NotifyERRORTitle = { link = "GruvboxRed" },
  --   NotifyINFOBorder = { link = "GruvboxAqua" },
  --   NotifyINFOIcon = { link = "GruvboxAqua" },
  --   NotifyINFOTitle = { link = "GruvboxAqua" },
  --   NotifyTRACEBorder = { link = "GruvboxGreen" },
  --   NotifyTRACEIcon = { link = "GruvboxGreen" },
  --   NotifyTRACETitle = { link = "GruvboxGreen" },
  --   NotifyWARNBorder = { link = "GruvboxYellow" },
  --   NotifyWARNIcon = { link = "GruvboxYellow" },
  --   NotifyWARNTitle = { link = "GruvboxYellow" },
  --   IlluminatedWordText = { link = "LspReferenceText" },
  --   IlluminatedWordRead = { link = "LspReferenceRead" },
  --   IlluminatedWordWrite = { link = "LspReferenceWrite" },
  --   TSRainbowRed = { fg = colors.red },
  --   TSRainbowOrange = { fg = colors.orange },
  --   TSRainbowYellow = { fg = colors.yellow },
  --   TSRainbowGreen = { fg = colors.green },
  --   TSRainbowBlue = { fg = colors.blue },
  --   TSRainbowViolet = { fg = colors.purple },
  --   TSRainbowCyan = { fg = colors.cyan },
  --   DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
  --   DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
  --   DapUIBreakpointsCurrentLine = { link = "GruvboxYellow" },
  --   DapUIBreakpointsDisabledLine = { link = "GruvboxGray" },
  --   DapUIBreakpointsInfo = { link = "GruvboxAqua" },
  --   DapUIBreakpointsLine = { link = "GruvboxYellow" },
  --   DapUIBreakpointsPath = { link = "GruvboxBlue" },
  --   DapUICurrentFrameName = { link = "GruvboxPurple" },
  --   DapUIDecoration = { link = "GruvboxPurple" },
  --   DapUIEndofBuffer = { link = "GruvboxBg2" },
  --   DapUIFloatBorder = { link = "GruvboxAqua" },
  --   DapUILineNumber = { link = "GruvboxYellow" },
  --   DapUIModifiedValue = { link = "GruvboxRed" },
  --   DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
  --   DapUIRestart = { fg = colors.green, bg = colors.bg1 },
  --   DapUIScope = { link = "GruvboxBlue" },
  --   DapUISource = { link = "GruvboxFg1" },
  --   DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
  --   DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
  --   DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
  --   DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
  --   DapUIStop = { fg = colors.red, bg = colors.bg1 },
  --   DapUIStoppedThread = { link = "GruvboxBlue" },
  --   DapUIThread = { link = "GruvboxBlue" },
  --   DapUIType = { link = "GruvboxOrange" },
  --   DapUIUnavailable = { link = "GruvboxGray" },
  --   DapUIWatchesEmpty = { link = "GruvboxGray" },
  --   DapUIWatchesError = { link = "GruvboxRed" },
  --   DapUIWatchesValue = { link = "GruvboxYellow" },
  --   DapUIWinSelect = { link = "GruvboxYellow" },
  --   NeogitDiffDelete = { link = "DiffDelete" },
  --   NeogitDiffAdd = { link = "DiffAdd" },
  --   NeogitHunkHeader = { link = "WinBar" },
  --   NeogitHunkHeaderHighlight = { link = "WinBarNC" },
  --   DiffviewStatusModified = { link = "GruvboxGreenBold" },
  --   DiffviewFilePanelInsertions = { link = "GruvboxGreenBold" },
  --   DiffviewFilePanelDeletions = { link = "GruvboxRedBold" },
  --   ["@comment"] = { link = "Comment" },
  --   ["@none"] = { bg = "NONE", fg = "NONE" },
  --   ["@preproc"] = { link = "PreProc" },
  --   ["@define"] = { link = "Define" },
  --   ["@operator"] = { link = "Operator" },
  --   ["@punctuation.delimiter"] = { link = "Delimiter" },
  --   ["@punctuation.bracket"] = { link = "Delimiter" },
  --   ["@punctuation.special"] = { link = "Delimiter" },
  --   ["@string"] = { link = "String" },
  --   ["@string.regex"] = { link = "String" },
  --   ["@string.regexp"] = { link = "String" },
  --   ["@string.escape"] = { link = "SpecialChar" },
  --   ["@string.special"] = { link = "SpecialChar" },
  --   ["@string.special.path"] = { link = "Underlined" },
  --   ["@string.special.symbol"] = { link = "Identifier" },
  --   ["@string.special.url"] = { link = "Underlined" },
  --   ["@character"] = { link = "Character" },
  --   ["@character.special"] = { link = "SpecialChar" },
  --   ["@boolean"] = { link = "Boolean" },
  --   ["@number"] = { link = "Number" },
  --   ["@number.float"] = { link = "Float" },
  --   ["@float"] = { link = "Float" },
  --   ["@function"] = { link = "Function" },
  --   ["@function.builtin"] = { link = "Special" },
  --   ["@function.call"] = { link = "Function" },
  --   ["@function.macro"] = { link = "Macro" },
  --   ["@function.method"] = { link = "Function" },
  --   ["@method"] = { link = "Function" },
  --   ["@method.call"] = { link = "Function" },
  --   ["@constructor"] = { link = "Special" },
  --   ["@parameter"] = { link = "Identifier" },
  --   ["@keyword"] = { link = "Keyword" },
  --   ["@keyword.conditional"] = { link = "Conditional" },
  --   ["@keyword.debug"] = { link = "Debug" },
  --   ["@keyword.directive"] = { link = "PreProc" },
  --   ["@keyword.directive.define"] = { link = "Define" },
  --   ["@keyword.exception"] = { link = "Exception" },
  --   ["@keyword.function"] = { link = "Keyword" },
  --   ["@keyword.import"] = { link = "Include" },
  --   ["@keyword.operator"] = { link = "GruvboxRed" },
  --   ["@keyword.repeat"] = { link = "Repeat" },
  --   ["@keyword.return"] = { link = "Keyword" },
  --   ["@keyword.storage"] = { link = "StorageClass" },
  --   ["@conditional"] = { link = "Conditional" },
  --   ["@repeat"] = { link = "Repeat" },
  --   ["@debug"] = { link = "Debug" },
  --   ["@label"] = { link = "Label" },
  --   ["@include"] = { link = "Include" },
  --   ["@exception"] = { link = "Exception" },
  --   ["@type"] = { link = "Type" },
  --   ["@type.builtin"] = { link = "Type" },
  --   ["@type.definition"] = { link = "Typedef" },
  --   ["@type.qualifier"] = { link = "Type" },
  --   ["@storageclass"] = { link = "StorageClass" },
  --   ["@attribute"] = { link = "PreProc" },
  --   ["@field"] = { link = "Identifier" },
  --   ["@property"] = { link = "Identifier" },
  --   ["@variable"] = { link = "GruvboxFg1" },
  --   ["@variable.builtin"] = { link = "Special" },
  --   ["@variable.member"] = { link = "Identifier" },
  --   ["@variable.parameter"] = { link = "Identifier" },
  --   ["@constant"] = { link = "Constant" },
  --   ["@constant.builtin"] = { link = "Special" },
  --   ["@constant.macro"] = { link = "Define" },
  --   ["@markup"] = { link = "GruvboxFg1" },
  --   ["@markup.strong"] = { bold = config.bold },
  --   ["@markup.emphasis"] = { italic = config.italic.emphasis },
  --   ["@markup.underline"] = { underline = config.underline },
  --   ["@markup.strike"] = { strikethrough = config.strikethrough },
  --   ["@markup.heading"] = { link = "Title" },
  --   ["@markup.raw"] = { link = "String" },
  --   ["@markup.math"] = { link = "Special" },
  --   ["@markup.environment"] = { link = "Macro" },
  --   ["@markup.environment.name"] = { link = "Type" },
  --   ["@markup.link"] = { link = "Underlined" },
  --   ["@markup.link.label"] = { link = "SpecialChar" },
  --   ["@markup.list"] = { link = "Delimiter" },
  --   ["@markup.list.checked"] = { link = "GruvboxGreen" },
  --   ["@markup.list.unchecked"] = { link = "GruvboxGray" },
  --   ["@comment.todo"] = { link = "Todo" },
  --   ["@comment.note"] = { link = "SpecialComment" },
  --   ["@comment.warning"] = { link = "WarningMsg" },
  --   ["@comment.error"] = { link = "ErrorMsg" },
  --   ["@diff.plus"] = { link = "diffAdded" },
  --   ["@diff.minus"] = { link = "diffRemoved" },
  --   ["@diff.delta"] = { link = "diffChanged" },
  --   ["@module"] = { link = "GruvboxFg1" },
  --   ["@namespace"] = { link = "GruvboxFg1" },
  --   ["@symbol"] = { link = "Identifier" },
  --   ["@text"] = { link = "GruvboxFg1" },
  --   ["@text.strong"] = { bold = config.bold },
  --   ["@text.emphasis"] = { italic = config.italic.emphasis },
  --   ["@text.underline"] = { underline = config.underline },
  --   ["@text.strike"] = { strikethrough = config.strikethrough },
  --   ["@text.title"] = { link = "Title" },
  --   ["@text.literal"] = { link = "String" },
  --   ["@text.uri"] = { link = "Underlined" },
  --   ["@text.math"] = { link = "Special" },
  --   ["@text.environment"] = { link = "Macro" },
  --   ["@text.environment.name"] = { link = "Type" },
  --   ["@text.reference"] = { link = "Constant" },
  --   ["@text.todo"] = { link = "Todo" },
  --   ["@text.todo.checked"] = { link = "GruvboxGreen" },
  --   ["@text.todo.unchecked"] = { link = "GruvboxGray" },
  --   ["@text.note"] = { link = "SpecialComment" },
  --   ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
  --   ["@text.warning"] = { link = "WarningMsg" },
  --   ["@text.danger"] = { link = "ErrorMsg" },
  --   ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
  --   ["@text.diff.add"] = { link = "diffAdded" },
  --   ["@text.diff.delete"] = { link = "diffRemoved" },
  --   ["@tag"] = { link = "Tag" },
  --   ["@tag.attribute"] = { link = "Identifier" },
  --   ["@tag.delimiter"] = { link = "Delimiter" },
  --   ["@punctuation"] = { link = "Delimiter" },
  --   ["@macro"] = { link = "Macro" },
  --   ["@structure"] = { link = "Structure" },
  --   ["@lsp.type.class"] = { link = "@type" },
  --   ["@lsp.type.comment"] = { link = "@comment" },
  --   ["@lsp.type.decorator"] = { link = "@macro" },
  --   ["@lsp.type.enum"] = { link = "@type" },
  --   ["@lsp.type.enumMember"] = { link = "@constant" },
  --   ["@lsp.type.function"] = { link = "@function" },
  --   ["@lsp.type.interface"] = { link = "@constructor" },
  --   ["@lsp.type.macro"] = { link = "@macro" },
  --   ["@lsp.type.method"] = { link = "@method" },
  --   ["@lsp.type.namespace"] = { link = "@namespace" },
  --   ["@lsp.type.parameter"] = { link = "@parameter" },
  --   ["@lsp.type.property"] = { link = "@property" },
  --   ["@lsp.type.struct"] = { link = "@type" },
  --   ["@lsp.type.type"] = { link = "@type" },
  --   ["@lsp.type.typeParameter"] = { link = "@type.definition" },
  --   ["@lsp.type.variable"] = { link = "@variable" },
  -- }

  -- My LOCAL fork
  local groups = {
    LineNr = { fg = "#303030", bg = "none"},
    CursorLine = { fg = "none", bg = "none"},
    CursorLineNr = { fg = "#fe0000", bg = "none", bold = true},
    TroubleFoldIcon = { fg = "#F98401", bg = "none"},

    Folded = { fg = "#cd0000", bg = "none"},
    FoldColumn = { fg = "#333333", bg = "none"},

    ["@keyword.directive"] = { fg="#454545" },


    -- Obsidian
    ["MyObsidianBullet"] = { fg="#454545" },
    ["ObsidianRefText"] = { fg="#fe0000", underline = false },


    -- whichkey
    [ "WhichKeyBorder"    ] =  { fg="#f95df9" },
    [ "WhichKeyFloat"     ] =  { fg="#fe0000" },
    [ "WhichKey"          ] =  { fg="#ff5f00" },
    [ "WhichKeyDesc"      ] =  { fg="#6C6C6C" },
    [ "WhichKeyGroup"     ] =  { fg="#875FFF" },
    [ "WhichKeySeperator" ] =  { fg="#5c5c5c" },

    -- specs
    [ "specs_colors"] =  { fg="#fe0000", bg="#fe0000" },

    -- lualine
    [ "lualinePath"  ] =  { fg="#444444", bold = true },
    [ "searchTotal"  ] =  { fg="#960006", bold = true },
    [ "searchCurrent"] =  { fg="#fe0301", bold = true },
    [ "vcsTagIcon"   ] =  { fg="#fe3c3c", bold = true },
    [ "vcsTagVers"   ] =  { fg="#ff00ff", bold = false },


    testg = { fg = "#fe0000", bg = "#fe0000"},
    fillBg = { fg = "#1c1c1c", bg = "none"},
    fillFg = { fg = "#fe0000", bg = "none"},
    inactiveFg = { fg = "#3c3c3c", bg = "none"},
    inactiveBg = { fg = "#000000", bg = "none"},
    bufFg = { fg = "#FF5555", bg = "none"},
    bufBg = { fg = "#090909", bg = "none"},
    bufBgSplit = { fg = "#222222", bg = "none"},
    bufVisFg = { fg = "#3A3A3A", bg = "none"},
    bufVisBg = { fg = "#1c1c1c", bg = "none"},
    inactiveCloseBtnFg = { fg = "#262626", bg = "none"},
    inactiveCloseBtnGg = { fg = "#000000", bg = "none"},
    tabSelFg = { fg = "#fe0000", bg = "none"},
    tabSelBg = { fg = "#1c1c1c", bg = "none"},
    tabFg = { fg = "#3A3A3A", bg = "none"},
    tabBg = { fg = "#1c1c1c", bg = "none"},
    dupVisFg = { fg = "#4F4FD0", bg = "none"},
    dupVisBg = { fg = "#1c1c1c", bg = "none"},
    SepFg = { fg = "#1c1c1c", bg = "none"},
    SepBG = { fg = "#1c1c1c", bg = "none"},
    sepSelFG = { fg = "#1c1c1c", bg = "none"},
    sepSelBG = { fg = "#1c1c1c", bg = "none"},
    SepVisFG = { fg = "#fe0000", bg = "none"},
    SepVisBG = { fg = "#fe0000", bg = "none"},
    MyBlackFG = { fg = "#1c1c1c", bg = "none"},
    MyBlackBG = { fg = "#000000", bg = "none"},
    MyInactiveBuf = { fg = "#090909", bg = "none"},
    MySeparator = { fg = "#121212", bg = "none"},
    separator = { fg = "#222222", bg = "none"},

    Buffer_secondary = { fg = "#fe0000", bg = "none"},
    tab_selected = { fg = "#fe0000", bg = "none"},
    tab = { fg = "#333333", bg = "none"},


    -- Bufferline
    [ "MyCurrBuff"     ] =  { fg="#d75fff", bold = true },
    [ "BufferLineBufferSelected" ] = { fg="#d75fff", bold = true},
    [ "MySecondaryActiveBuf"     ] =  { fg="#454545", bold = true },
    [ "BufferLineBackground"     ] =  { fg="#454545", bold = true },
    [ "BufferLineModifiedVisible"     ] =  { fg="#fe0000" },
    [ "BufferLineIndicatorSelected"   ] =  { fg="#fc2c2c" },
    [ "BufferLineTabSeparatorSelected"] =  { fg="#1c1c1c" },
    [ "BufferLineTabSeparator"        ] =  { fg="#1c1c1c" },
    [ "BufferLineSeparator"           ] =  { fg="#b50104" },
    [ "BufferLineDuplicate"           ] =  { fg="#cd0000", bold = true, italic = false },

    [ "BufferLineFill"             ] =  { fg="#cd0000", bold = true },
    [ "BufferLineBufferVisible"    ] =  { fg="#ff5f00", bold = true , italic = false},
    [ "BufferLineDuplicateSelected"] =  { fg="#ff5f00", sp="#00AFFF", bold = true},
    [ "BufferLinePick"             ] =  { fg="#ff5f00", bg="#000000", bold = true},
    [ "BufferLinePickSelected"     ] =  { fg="#3c3c3c", bg="none"   , bold = true},

    -- others
    [ "Special"         ] =  { fg="#5FAFFF", bold = true },
    [ "SpecialChar"     ] =  { fg="#5c5c5c", bold = true },
    [ "Function"        ] =  { fg="#3396f9", bold = false},
    [ "Keyword"         ] =  { fg="#5F5fFF", bold = true },
    [ "Boolean"         ] =  { fg="#D75FFF", bold = true },
    [ "Keywordreturn"   ] =  { fg="#D75FFF", bold = true },
    [ "NormalVariable"  ] =  { fg="#00afff", bold = true },
    [ "pythonStatement" ] =  { fg="#d75fff", bold = true },
    [ "Include"         ] =  { fg="#c25fc2", bold = true },
    [ "PreProc"         ] =  { fg="#c25fc2", bold = true },
    [ "Number"          ] =  { fg="#FF5F00", bold = true, italic = true },
    [ "yamlFlowString"] =  { link = "TSstring"},
    [ "yamlBool"      ] =  { link = "TSBoolean" },

    Identifier       = { fg = "#5f5fff", bg                     = "none"},
    myVarBuiltin     = { fg = "#514ed5", bg                    = "none"},
    yamlPlainScalar  = { fg = "#fe0000", bg                     = "none"},
    normal           = { fg = "#b2b2b2", bg                     = "#090909"},
    fileWritable     = { fg = "#D0540B", bg                     = "none"},
    fileCwd          = { fg = "#13557B", bg                     = "none"},
    fileCwdDir       = { fg = "#444444", bg                     = "none"},
    modifiedIcon     = { fg = "#d75fff", bg                     = "none"},
    redBold          = { fg = "#fe0000", bg                     = "none"},
    fileReadOnlyIcon = { fg = "#d75ff0", bg                     = "none"},
    encodingAlert    = { fg = "#fe0000", bg                     = "none"},
    wrongEncoding    = { fg = "#4c4c4c", bg                     = "none"},
    Search           = { fg = "#fe0000", bg                     = "none", undercurl = true},
    search_lualine   = { fg = "#bf00be"            , bg         = "none"},
    search_quotation = { fg = "#3c3c3c"          , bg           = "none"},
    IncSearch        = { fg = "#FF0000", bg                     = "none"    },
    MatchParen       = { fg = "#e3fF00", bg                     = "#2c2c2c"},
    Comment          = { fg = "#4c4c4c"                    , bg = "none"},
    ghostComment     = { fg = "#404040"               , bg      = "none"},
    SpecialComment   = { fg = "#444444"             , bg        = "none"},
    VertSplit        = { fg = "#555555", bg                     = "none"},
    StatusLineNC     = { fg = "#E3F568", bg                     = "none"},
    StatusLine       = { fg = "#E3F568", bg                     = "none"},
    todo             = { fg = "yellow", bg                      = "none"},
    ModeMsg          = { fg = "#fc3c3c", bg                     = "none"},
    MsgArea          = { fg = "#4f4f4f", bg                     = "none"},

    [ '@storageclass'] =  { fg="#5f5fff", bold = true },

    DiffChange     = { fg = "none", bg    = "none"},
    DiffAdd        = { fg = "#349e34", bg = "none"},
    Floaterm       = { fg = "#9E9E9E", bg    = "none"},
    FloatermBorder = { fg = "#0087FF", bg    = "none"},
    NormalFloat    = { fg = "#8c8c8c", bg    = "none"},

    -- Mini
    [ "MiniIndentscopeSymbol"] =  { fg="#fe0000", bold = true },
    [ "MiniIndentscopeSymbolOff"] =  { fg="#fff000", bold = true },

    -- dashboard
    [ "DashboardHeader"] =  { fg="#5f5f87", bold = true },
    [ "DashboardFooter"] =  { fg="#4c4c4c", bold = true },

    -- neorg
    [ "@neorg.anchors.declaration" ] =  { fg="#ac4cce", bold = true, italic = true },
    [ "@neorg.links.location.url"  ] =  { fg="#ac4cce", bold = true, italic = true },
    [ "@neorg.links.file"          ] =  { fg="#d75fff", bold = true },
    [ "@neorg.links.description"   ] =  { fg="#5f5f5f"},

    [ "@neorg.headings.1.title"               ] =  { fg="#d75fff", bold = true },
    [ "@neorg.headings.1.prefix"              ] =  { fg="#fe0000" },
    [ "@neorg.headings.2.title"               ] =  { fg="#ff5f00", bold = true },
    [ "@neorg.headings.2.prefix"              ] =  { fg="#d70000" },
    [ "@neorg.headings.3.title"               ] =  { fg="#cd0000", bold = true },
    [ "@neorg.headings.3.prefix"              ] =  { fg="#5f5f5f", bold = true },
    [ "@neorg.headings.4.title"               ] =  { fg="#ac4cce", bold = true },
    [ "@neorg.headings.4.prefix"              ] =  { fg="#ac4cce" },
    [ "@neorg.headings.5.title"               ] =  { fg="#5c5c5c", bold = true },
    [ "@neorg.headings.5.prefix"              ] =  { fg="#5c5c5c" },
    [ "@neorg.todo_items.done"                ] =  { fg="#00d700" },
    [ "@neorg.todo_items.undone"              ] =  { fg="#fe0000" },
    [ "@neorg.lists.unordered.prefix"         ] =  { fg="#5f5f87" },
    [ "@neorg.tags.ranged_verbatim.code_block"] =  { bg="#111111", blend=50},
    [ "@neorg.definitions.title"              ] =  { fg="#a545c8", bold = true},
    [ "@neorg.definitions.prefix"             ] =  { fg="#cd0000", bold = true},
    [ "@neorg.markup.bold"                    ] =  { fg="#ff5f00", bold = true },
    [ "@neorg.markup.italic"                  ] =  { fg="#00afff", italic = true },
    [ "@neorg.markup.verbatim"                ] =  { fg="#5f5f87", bg="#3a1f12", italic = true},
    [ "@neorg.lists.ordered.prefix"           ] =  { fg="#d75fff", bold = true ,italic = true},

    -- telescope
    [ "TelescopeBorder"          ] =  {fg="#8700ff" },
    [ "TelescopePromptBorder"    ] =  {fg="#8700ff" },
    [ "TelescopePreviewMatch"    ] =  {fg="#fff000" },
    [ "TelescopeNormal"          ] =  {fg="#444444" },
    [ "TelescopePromptCounter"   ] =  {fg="#444444" },
    [ "TelescopeMultiIcon"       ] =  {fg="#646608", bg="none" },
    [ "TelescopePromptNormal"    ] =  {fg="#fe0000", bg="none" },
    [ "TelescopeSelectionCaret"  ] =  {fg="#f95df9", bg="none" },
    [ "TelescopeMatching"        ] =  {fg="#ff5f00", bold = true },
    [ "TelescopePromptPrefix"    ] =  {fg="#fe0000", bold = true },
    [ "TelescopePreviewDirectory"] =  {fg="#fe0000", bold = true },
    [ "pythonVirtualEnv"         ] =  {fg="#875fff", bold = true },
    [ "pythonVirtualEnvIcon"     ] =  {fg="#b80b0b", bold = true },
    [ "pythonVirtualEnvBracket"  ] =  {fg="#ff5f00", bold = true },
    [ "TelescopePromptTitle"     ] =  {fg="#b80b0b", italic = true },
    [ "TelescopeSelection"       ] =  {fg="#f95df9", bg="none", bold = true },
    [ "TelescopePreviewDate"     ] =  {fg="#3c3c3c", bg="none", bold = true },
    [ "TelescopePreviewSize"     ] =  {fg="#646608", bg="none", bold = true },

    -- TS
    [ "String"          ] =  { fg="#FF0000"},
    [ "Operator"        ] =  { fg="#d484ff"},
    [ "TSError"         ] =  { fg="#fe0000"},
    [ "shDerefWordError"] =  { fg="none"   , bg="none"},
    [ "ErrorMsg"        ] =  { fg="#9742b4", bg="none", bold = true },

    -- lazy
    [ "LazyProp"             ] =  { fg="#ff0000", bg= "none", bold = true},
    [ "LazyDimmed"           ] =  { fg="#ff0000", bg= "none", bold = true},
    [ "LazySpecial"          ] =  { fg="#fe0000", bg= "none", bold = true},
    [ "LazyH1"               ] =  { fg="#ff5f00", bg= "#3c3c3c", bold = true},
    [ "LazyButtonActive"     ] =  { link = "lazyH1"},

    -- zsh
    [ "zshVariableDef"] =  { fg="#d75fff" },
    [ "zshParentheses"] =  { fg="#fe0000" },
    [ "zshFunction"] =  { fg="#5f5fff", bold = true },
    [ "zshBrackets"] =  { fg="#5f5fff", bold = true },
    [ "zshOperator"] =  { fg="#ff5f00", bold = true },
    [ "fileName"] =     { fg="#d70000", italic = true },

    -- ibl
    [ "IblIndent"     ] =  { fg="#303030" },
    [ "IblWhitespace" ] =  { fg="#303030" },
    [ "IblScope"      ] =  { fg="#c64b11" },

    ['@function']= { fg='#5fafff'},
    ['@comment']= {link = 'Comment'},
    ['@error']= {link = 'TSError'},
    ['@preproc']= {link = 'PreProc'},
    ['@operator']= { fg="#fe0000", bold = true},
    ['@string']= {link = 'String'},
    ['@string.escape']= {link = 'SpecialChar'},
    ['@boolean']= {link = 'Boolean'},
    ['@number']= {link = 'Number'},
    ['@function.call']=    { fg="#ff00ff", nocombine = true },
    ['@function.builtin']= { fg="#875fff", nocombine = true },
    ['@method.call']= {link = 'Function'},
    ['@method']= { fg="#3396f9", bold = true, italic = true },
    ['@keyword']=          { fg="#d75fff", bold = true , italic = true },
    ['@keyword.function']= { fg="#5f5fff", bold = false, italic = true },
    ['@keyword.return']= { fg="#c25fc2", bold = true, italic = true },
    ['@repeat']= { fg="#d70000", bold = true },
    ['@include']= { fg="#c25fc2", bold = true, italic = true},
    ['@type.builtin']= {link = 'Type'},
    ['@type.qualifier']= { fg="#bf00be", italic = true},
    ['@attribute']= {fg="#fe4c4c", bold = true, italic = true},
    ['@property']= {link = 'Identifier'},
    ['@variable']=         { fg='#fe00d5' },
    ['@namespace']= {link = 'Include'},
    ['@text.quote']= {fg="#6c6c6c", bold = true},
    ['@text.note']= {link = 'SpecialComment'},

    -- navbuddy
    [ "NavbuddyCursorLine"    ] =  { bold = false, reverse = true },
    [ "NavbuddyClass"    ] =  { fg="#FF5F00" },

    --notify
    NotifyERRORBody = { fg = "#d75fff", bg = "none"},
    NotifyBackground = { fg = "none", bg = "#000000"},
    NotifyERRORIcon = { fg = "#fe0000", bg = "none"},
    NotifyWARNIcon = { fg = "#FF5F00", bg = "none"},
    NotifyINFOIcon = { fg = "#878700", bg = "none"},
    NotifyDEBUGIcon = { fg = "#8B8B8B", bg = "none"},
    NotifyTRACEIcon = { fg = "#d484ff", bg = "none"},
    NotifyERRORTitle = { fg = "#fe0000", bg = "none"},
    NotifyWARNTitle = { fg = "#FF5F00", bg = "none"},
    NotifyINFOTitle = { fg = "#13AA13", bg = "none"},
    NotifyDEBUGTitle = { fg = "#8B8B8B", bg = "none"},
    NotifyTRACETitle = { fg = "#D484FF", bg = "none"},
    NotifyWARNBorder = { fg = "#ff5f00", bg = "none"},
    NotifyERRORBorder = { fg = "#fe0000", bg = "none"},
    NotifyINFOBorder = { fg = "#646608", bg = "none"},
    NotifyDEBUGBorder = { fg = "#8B8B8B", bg = "none"},
    NotifyTRACEBorder = { fg = "#8B8B8B", bg = "none"},

    -- rainbow
    [ "RainbowDelimiterRed"   ] =  { fg="#5FAFFF" },
    [ "RainbowDelimiterOrange"] =  { fg="#5F5FFF" },
    [ "RainbowDelimiterYellow"] =  { fg="#833D9B" },
    [ "RainbowDelimiterGreen" ] =  { fg="#FF5F00" },
    [ "RainbowDelimiterCyan"  ] =  { fg="#cd0000" },
    [ "RainbowDelimiterBlue"  ] =  { fg="#35AA35" },
    [ "RainbowDelimiterViolet"] =  { fg="#458588" },


    -- gitsigns
    GitSignsCurrentLineBlame = { fg = "#3c3c3c", bg = "none"},
    GitSignsAdd = { fg = "#45d44a", bg = "none"},
    GitSignsAddInline = { fg = "#45d44a", bg = "none"},
    GitSignsAddLn = { fg = "#45d44a", bg = "none"},
    GitSignsAddLnVirtLn = { fg = "#45d44a", bg = "none"},
    GitSignsAddLnInline = { fg = "#45d44a", bg = "none"},
    GitSignsChange = { fg = "#AD530E", bg = "none"},
    GitSignsChangeDel = { fg = "#353535", bg = "none"},
    GitSignsChangeInline = { fg = "#AD530E", bg = "none"},
    GitSignsDelete = { fg = "#cd0000", bg = "none"},
    GitSignsDeleteLn = { fg = "#4c4c4c", bg = "none"},
    GitSignsDeleteInline = { fg = "#4c4c4c", bg = "none"},
    GitSignsUntracked = { fg = "#ff00ff", bg = "none"},

    -- flog / codi
    [ "CodiVirtualText"    ] =  { fg="#4c4c4c" },
    [ "flogDate"    ] =  { fg="#4c4c4c", bold = true },
    [ "flogHash"    ] =  { fg="#cb08d1", italic = false },
    [ "flogAuthor"  ] =  { fg="#5f5f87", italic = false },
    [ "flogBranch1" ] =  { fg="#8800ff", bold = true },
    [ "flogBranch2" ] =  { fg="#0086d9", bold = true },
    [ "flogBranch3" ] =  { fg="#036fb5", bold = true },
    [ "flogBranch4" ] =  { fg="#075488", bold = true },
    [ "flogBranch5" ] =  { fg="#5f5f87", bold = true },
    [ "flogBranch6" ] =  { fg="#084773", bold = true },
    [ "flogBranch7" ] =  { fg="#083759", bold = true },
    [ "flogCommit"  ] =  { fg="#8800ff", bold = true },

    -- neotree
    [ "NeoTreeRootName"     ] =  { fg="#3c3c3c" },
    [ "NeoTreeBufferNumber" ] =  { fg="#970303" },
    [ "NeoTreeIndentMarker" ] =  { fg="#3c3c3c" },
    [ "NeoTreeDirectoryIcon"] =  { fg="#b13738" },
    [ "NeoTreeDirectoryName"] =  { fg="#5f5f87", bold = true },
    [ "NeoTreeFileName"     ] =  { fg="#5c5c5c" },
    [ "NeoTreeModified"     ] =  { fg="#fe0000" },
    [ "NeoTreeFileIcon"     ] =  { fg="#cd0000" },
    [ "NeoTreeGitConflict"  ] =  { fg="#ff8700" },
    [ "NeoTreeGitUnstaged"  ] =  { fg="#cd0000", bold = true },
    [ "NeoTreeGitAdded"     ] =  { fg="#745511", bold = true },
    [ "NeoTreeGitUntracked" ] =  { fg="#fe0000", bold = true },
    [ "NeoTreeGitModified"  ] =  { fg="#cd4e11", bold = true },
    [ "NeoTreeCursorLine"   ] =  { bg="#151515", bold = false},
    [ "NeoTreeMessage"      ] =  { fg="#333333", bold = true, italic = true },

    -- ibl / dap
    [ "IndentBlanklineIndent1"     ] =  { fg="#1c1c1c", nocombine = true },
    [ "IndentBlanklineIndent2"     ] =  { fg="#1c1c1c", nocombine = true },
    [ "IndentBlanklineIndent3"     ] =  { fg="#1c1c1c", nocombine = true },
    [ "IndentBlanklineIndent4"     ] =  { fg="#1c1c1c", nocombine = true },
    [ "IndentBlanklineIndent5"     ] =  { fg="#1c1c1c", nocombine = true },
    [ "IndentBlanklineIndent6"     ] =  { fg="#1c1c1c", nocombine = true },
    [ "IndentBlanklineChar"        ] =  { fg="#303030", nocombine = true },
    [ "IndentBlanklineContextChar" ] =  { fg="#FF5F00", nocombine = true },
    [ "DapBreakingPoint"] =  { fg="#ff5f00", nocombine = true },
    [ "DapStopped"      ] =  { fg="#ff00ff", nocombine = true },

    -- diffview
    [ "DiffviewFilePanelFileName" ] =  { fg="#d70000" },
    [ "DiffviewNonText"           ] =  { fg="#1c1c1c" },
    [ "diffAdded"                 ] =  { fg="#3bb63b", bold = true },
    [ "diffRemoved"               ] =  { fg="#fe0000", bold = true },
    [ "DiffDelete"                ] =  { fg="#444444", bold = true },
    [ "DiffviewFolderName"        ] =  { fg="#3c3c3c", bold = true },
    [ "DiffviewFolderSign"        ] =  { fg="#5c5cff", bold = true },
    [ "DiffviewStatusModified"    ] =  { fg="#d70000", bold = true },
    [ "DiffviewSecondary"         ] =  { fg="#5f5fff", bold = true },
    [ "DiffviewFilePanelSelected" ] =  { fg="#d75fff", bold = true },
    [ "DiffviewFilePanelPath"     ] =  { fg="#3c3c3c", italic = true },
    [ "DiffviewDiffAddAsDelete"   ] =  { fg="#444444", bg="#5c5cff" },
    [ "DiffviewCursorLine"        ] =  { bg="#4c4c4c", fg="#d75fff" },
    [ "DiffText"                  ] =  { fg="#ff8700", bg="#b50104", bold = true },

    --fzf
    fzfselected = { fg = "#d70000", bg = "none"},
    FzFfg = { fg = "#3c3c3c", bg = "none"},
    fzfpointer = { fg = "#FF5F00", bg = "none"},
    fzfHlPlus = { fg = "#FF8700", bg = "none"},
    fzfSpinner = { fg = "#5fd7ff", bg = "none"},
    fzfComment = { fg = "#444444", bg = "none"},
    fzfhl = { fg = "#AD6009", bg = "none"},
    fzfInfo = { fg = "#fe0000", bg = "none"},
    fzfMarker = { fg = "#0077ff", bg = "none"},
    fzf_border_fg = { fg = "#0087FF", bg = "none"},
    fzf_border_bg = { fg = "none", bg = "NONE"},
    fzf_border_bgPlus = { fg = "none", bg = "#121212"},
    fzf1 = { fg = "#5C5CFF", bg = "None"},
    fzf2 = { fg = "#5C5CFF", bg = "None"},
    fzf3 = { fg = "#5C5CFF", bg = "None"},

    -- lspsaga
    [ "SagaWinbarFilename"  ] =  { fg="#fe0000", bold = true },
    [ "SagaWinbarFileIcon"  ] =  { fg="#fe0000", bold = false },
    [ "SagaWinbarFolderName"] =  { fg="#5c5c5c", bold = true },
    [ "SagaWinbarFolder"    ] =  { fg="#5c5c5c", bold = true },
    [ "SagaFolder"          ] =  { fg="#5c5c5c", bold = true },

    -- lspsaga winbar
    [ "SagaBorder"]                  = { fg = "#f95df9", bold = true },
    SagaWinbarInterface              = { fg = "#bf00be", bg   = "none"},
    SagaWinbarConstructor            = { fg = "#5fafff", bg   = "none"},
    SagaWinbarStruct                 = { fg = "#bf00be", bg   = "none"},
    SagaWinbarObject                 = { fg = "#bf00be", bg   = "none"},
    SagaWinbarUnit                   = { fg = "#ff5f00", bg   = "none"},
    SagaWinbarFile                   = { fg = "#5fafff", bg   = "none"},
    SagaWinbarSnippet                = { fg = "#00afff", bg   = "none"},
    SagaWinbarText                   = { fg = "#fe0000", bg   = "none"},
    SagaWinbarTypeAlias              = { fg = "#bf00be", bg   = "none"},
    SagaWinbarEvent                  = { fg = "#c17b7b", bg   = "none"},
    SagaWinbarParameter              = { fg = "#49a1bf", bg   = "none"},
    SagaWinbarKey                    = { fg = "#c17b7b", bg   = "none"},
    SagaWinbarValue                  = { fg = "#00afff", bg   = "none"},
    SagaWinbarMacro                  = { fg = "#c25fc2", bg   = "none"},
    SagaWinbarNumber                 = { fg = "#ff5f00", bg   = "none"},
    SagaWinbarConstant               = { fg = "#3390f0", bg   = "none"},
    SagaWinbarFunction               = { fg = "#3396f9", bg   = "none"},
    SagaWinbarEnum                   = { fg = "#ff5f00", bg   = "none"},
    SagaWinbarField                  = { fg = "#49a1bf", bg   = "none"},
    SagaWinbarProperty               = { fg = "#49a1bf", bg   = "none"},
    SagaWinbarMethod                 = { fg = "#3396f9", bg   = "none"},
    SagaWinbarClass                  = { fg = "#c25fc2", bg   = "none"},
    SagaWinbarPackage                = { fg = "#5fd7ff", bg   = "none"},
    SagaWinbarStaticMethod           = { fg = "#3396f9", bg   = "none"},
    SagaWinbarTypeParameter          = { fg = "#49a1bf", bg   = "none"},
    SagaWinbarEnumMember             = { fg = "#ff5f00", bg   = "none"},
    SagaWinbarOperator               = { fg = "#d484ff", bg   = "none"},
    SagaWinbarNull                   = { fg = "#c17b7b", bg   = "none"},
    SagaWinbarNamespace              = { fg = "#c25fc2", bg   = "none"},
    SagaWinbarArray                  = { fg = "#bf00be", bg   = "none"},
    SagaWinbarBoolean                = { fg = "#d75fff", bg   = "none"},
    SagaWinbarString                 = { fg = "#ff0000", bg   = "none"},
    SagaWinbarVariable               = { fg = "#00afff", bg   = "none"},
    SagaWinbarSep                    = { fg = "#d484ff", bg   = "none"},
    LspSagaCodeActionTitle           = { fg = "#fe0000", bg   = "none"},
    LspSagaCodeActionContent         = { fg = "#7F7F7F", bg   = "none"},
    LspDiagnosticsDefaultError       = { fg = "#ff0000", bg   = "none"},
    LspDiagnosticsDefaultHint        = { fg = "#ff5f00", bg   = "none"},
    LspDiagnosticsDefaultWarning     = { fg = "#FFD700", bg   = "none"},
    LspDiagnosticsDefaultInformation = { fg = "#00D700", bg   = "none"},
    LspSagaDiagnosticHeader          = { fg = "#FF5F00", bg   = "none"},
    LspSagaRenameBorder              = { fg = "#0087FF", bg   = "NONE"},
    LspSagaDefPreviewBorder          = { fg = "#0087FF", bg   = "NONE"},
    LspSagaLspFinderBorder           = { fg = "#0087FF", bg   = "NONE"},
    LspSagaSignatureHelpBorder       = { fg = "#0087FF", bg   = "NONE"},
    LspSagaCodeActionBorder          = { fg = "#0087FF", bg   = "NONE"},
    LspSagaHoverBorder               = { fg = "#0087FF", bg   = "NONE"},
    LspSagaDocTruncateLine           = { fg = "#121212", bg   = "none"},
    LspSagaDiagnosticTruncateLine    = { fg = "#121212", bg   = "none"},
    LspSagaShTruncateLine            = { fg = "#121212", bg   = "none"},
    LspSagaCodeActionTruncateLine    = { fg = "#121212", bg   = "none"},
    LspFloatWinBorder                = { fg = "#0087FF", bg   = "NONE"},
    LspSagaBorderTitle               = { fg = "#0087FF", bg   = "NONE"},
    LspSagaDiagnosticBorder          = { fg = "#0087FF", bg   = "NONE"},
    LspDiagnosticsFloatingWarn       = { fg = "#0087FF", bg   = "NONE"},
    LspDiagnosticsFloatingInfor      = { fg = "#0087FF", bg   = "NONE"},
    LspSagaAutoPreview               = { fg = "#FF0000", bg   = "NONE"},
    LspSagaLightBulbSign             = { fg = "#FF5F00", bg   = "NONE"},
    LspSagaLightBulb                 = { fg = "#FFD700", bg   = "none"},
    DefinitionPreviewTitle           = { fg = "#fe0000", bg   = "none"},
    LspSagaFinderSelection           = { fg = "#878700", bg   = "none"},
    LspFloatWinNormal                = { fg = "none", bg      = "NONE"},
    TargetWord                       = { fg = "#fe0000", bg   = "none"},
    DefinitionIcon                   = { fg = "#0087ff", bg   = "none"},
    ReferencesIcon                   = { fg = "#46D146", bg   = "none"},
    DefinitionCount                  = { fg = "#0087ff", bg   = "none"},
    ReferencesCount                  = { fg = "#46D146", bg   = "none"},

    -- lsp_signature / hop
    mySigLabel  = { fg = "#FFD700", bg = "none"},
    hiParameter = { fg = "#fe0000", bg = "none"},
    myHint      = { fg = "#fe0000", bg = "none"},
    HopNextKey  = { fg = "#FF5F00", bg = "none",   bold = true },
    HopNextKey1 = { fg = "#8E6EEF", bg = "none",   bold = true },
    HopNextKey2 = { fg = "#4848B9", bg = "none",   bold = true },
    hopcursor   = { fg = "none", bg    = "#121212",bold = true },

    -- signify / wiki
    SignifyLine                = { fg = "#FF5555", bg = "none"},
    SignColumn                 = { fg = "#FF5555", bg = "none"},
    SignifyLineChange          = { fg = "#FF5555", bg = "none"},
    SignifyLineDelete          = { fg = "#fe0000", bg = "#252525"},
    SignifyLineDeleteFirstLine = { fg = "#fe0000", bg = "none"},
    SignifySignAdd             = { fg = "#00AFFF", bg = "none"},
    SignifySignDelete          = { fg = "#fe0000", bg = "none"},
    SignifySignDeleteFirstLine = { fg = "#fe0000", bg = "none"},
    SignifySignChange          = { fg = "#ff5f00", bg = "none"},
    SignifySignChangeDelete    = { fg = "#fe0000", bg = "none"},
    VimwikiHeader1             = { fg = "#FF0000", bg = "none"},
    VimwikiHeader2             = { fg = "#FFD700", bg = "none"},
    VimwikiHeader3             = { fg = "#875FFF", bg = "none"},
    VimwikiHeaderChar          = { fg = "#5C5CFF", bg = "none"},
    VimwikiLink                = { fg = "#5FAFFF", bg = "none"},
    VimwikiListTodo            = { fg = "#5FAFFF", bg = "none"},
    SignifyLineChangeDelete    = { fg = "#fe0000", bg = "none"},

    -- html
    htmlItalic = { fg = "#5F87FF", bg = "none"},
    htmlBold = { fg = "#c93a05", bg = "none"},

    --fidget
    [ "FloatBorder"   ] =  { fg="#fe0000", blend=0},
    [ "FidgetTitle"   ] =  { fg="#fe1f9d", bold = true, blend=0},
    [ "FidgetTask"    ] =  { fg="#711e1d", bold = true, blend=0},
    [ "fidget_status" ] =  { fg="#fe1f9d", bold = true, blend=0},
    [ "fidget_task"   ] =  { fg="#711e1d", bold = true, blend=0},


    -- illuminate / treesitter
    IlluminatedWordRead = {  bg = "#2c2c2c", fg = "none"},
    IlluminatedWordText = {  bg = "#2c2c2c", fg = "none"},
    IlluminatedWordWrite = { bg = "#2c2c2c", fg ="none"},
    -- TSFuncMacro = { fg = "#ffff60", bg = "none"},
    TSVariable = { fg = "#5FD7FF", bg = "none"},
    TSVariableSymbol = { fg = "#626262", bg = "none"},
    TSPunctBracket = { fg = "#5FAFFF", bg = "none"},
    TSFunction = { fg = "#5FAFFF", bg = "none"},
    TSPunctDelimiter = { fg = "#5FD7FF", bg = "none"},
    TSKeywordReturn = { fg = "#5FAFFF", bg = "none"},
    TSKeyword = { fg = "#5f5fff", bg = "none"},
    TSNamespace = { fg = "#FF5F00", bg = "none"},
    TSStringEscape = { fg = "#FF0000", bg = "none"},
    TSNumber = { fg = "#00D700", bg = "none"},
    TSBoolean = { fg = "#D75FFF", bg = "none"},
    TSString = { fg = "#FF5F00", bg = "none"},
    TSType = { fg = "#5FAFFF", bg = "none"},
    TSOperator = { fg = "none", bg = "none"},
    TSRepeat = { fg = "#5FD7FF", bg = "none"},
    TSPunctSpecial = { fg = "Magenta", bg = "none"},
    TSConstant = { fg = "#3396f9", bg = "none"},
    TSConstructor = { fg = "#FFD700", bg = "none"},
    TSKeywordOperator = { fg = "#FF5F00", bg = "none"},
    Constant = { fg = "#3396f9", bg = "none"},

    cppTSKeyword = { fg = "#3396f9", bg = "none"},
    cppTSConstructor = { fg = "#5fafff", bg = "none"},
    cppTSType = { fg = "#5f5fff", bg = "none"},
    javascriptTSKeyword = { fg = "#5F5FFF", bg = "none"},
    javascriptTSMethod = { fg = "#3396f9", bg = "none"},
    TSKeywordFunction = { fg = "#5FAFFF", bg = "none"},
    TSVariableBuiltin = { fg = "#5FAFFF", bg = "none"},
    TSProperty = { fg = "#5C5CE3", bg = "none"},
    javascriptTSPunctSpecial = { fg = "#FF0000", bg = "none"},
    javascriptTSConditional = { fg = "#5FAFFF", bg = "none"},
    pythonTSFuncBuiltin = { fg = "#3396f9", bg = "none"},
    pythonTSMethod = { fg = "#5FAFFF", bg = "none"},
    pythonTSInclude = { fg = "#5f5fff", bg = "none"},
    lspSagaModule = { fg = "#3396f9", bg = "none"},
    lspSagaFunction = { fg = "#3396f9", bg = "none"},
    lspSagaArray = { fg = "#3396f9", bg = "none"},

    TSFuncMacro = { fg = "#00AFFF", bg = "none"},
    vimEnvvar = { fg = "#5FD7FF", bg = "none"},
    Statement = { fg = "#5FD7FF", bg = "none"},
    vimTSVariableBuiltin = { fg = "#5fafff", bg = "none"},
    vimTSKeyword = { fg = "#5f5fff", bg = "none"},
    vimTSNamespace = { fg = "#3396F9", bg = "none"},
    TSURI = { fg = "#FF5F00", bg = "none"},
    TSTITLE = { fg = "#ff8700", bg = "none"},
    TSTagDelimiter = { fg = "#626262", bg = "none"},
    TSTag = { fg = "#5f5fff", bg = "none"},
    Type = { fg = "#bf00be", bg = "none"},
    TSTagAttribute = { fg = "#D70000", bg = "none"},
    htmlTSOperator = { fg = "#D70000", bg = "none"},
    TreesitterContext = { fg = "#151515", bg = "none"},
    TreesitterContextLineNumber = { fg = "#d75fff", bg = "none"},
    TSDefinitionUsage = { fg = "#FF8700", bg = "#2c2c2c"},
    TSDefinition = { fg = "#FF8700", bg = "#2c2c2c"},


    LspInfoFiletype = { fg = "#FF8700", bg = "none"},
    LspInfoList = { fg = "#D70000", bg = "none"},
    LspInfoTip = { fg = "#fe0000", bg = "none"},
    LspInfoTitle = { fg = "#fe0000", bg = "none"},
    LspInfoBorder = { fg = "#0087FF", bg = "none"},


    MasonHighlightBlockBold = { fg = "#fe0000", bg = "none"},
    MasonMutedBlock = { fg = "#4c4c4c", bg = "none"},
    MasonHeader = { fg = "#ffd700", bg = "none"},
    MasonNormal = { fg = "#555555", bg = "none"},
    MasonHighlight = { fg = "#ff0000", bg = "none"},
    Underlined = { fg = "#80a0ff", bg = "none"},

    [ "@markup.heading.1"] =  { fg="#fe0000",  bold = true },
    [ "@markup.heading.2"] =  { fg="#fe0000",  bold = true },
    [ "@markup.heading.3"] =  { fg="#fe0000",  bold = true },
    [ "@markup.heading.4"] =  { fg="#fe0000",  bold = true },
    [ "@markup.heading.5"] =  { fg="#fe0000",  bold = true },
    [ "@markup.heading.6"] =  { fg="#fe0000",  bold = true },
    [ "@markup.heading.1.marker"] =  { fg="#fe0000",  bold = true },
    [ "@markup.heading.2.marker"] =  { fg="#fe0000",  bold = true },
    [ "@markup.heading.3.marker"] =  { fg="#fe0000",  bold = true },
    [ "@markup.heading.4.marker"] =  { fg="#fe0000",  bold = true },
    [ "@markup.heading.5.marker"] =  { fg="#fe0000",  bold = true },
    [ "@markup.heading.6.marker"] =  { fg="#fe0000",  bold = true },
    [ "@text.title.1"        ] =  { fg="#fe0000",  bold = true },
    [ "@text.title.1.marker" ] =  { fg="#fe0000",  bold = true },
    [ "@text.title.2"        ] =  { fg="#fe0000",  bold = true },
    [ "@text.title.2.marker" ] =  { fg="#fe0000",  bold = true },
    [ "@text.title.3"        ] =  { fg="#fe0000",  bold = true },
    [ "@text.title.3.marker" ] =  { fg="#fe0000",  bold = true },
    [ "@text.title.4"        ] =  { fg="#fe0000",  bold = true },
    [ "@text.title.4.marker" ] =  { fg="#fe0000",  bold = true },
    [ "@text.title.5"        ] =  { fg="#fe0000",  bold = true },
    [ "@text.title.5.marker" ] =  { fg="#fe0000",  bold = true },
    [ "@text.title.6"        ] =  { fg="#fe0000",  bold = true },
    [ "@text.title.6.marker" ] =  { fg="#fe0000",  bold = true },
    [ "@text.title.7"        ] =  { fg="#fe0000",  bold = true },
    [ "@text.title.7.marker" ] =  { fg="#fe0000",  bold = true },
    [ "@markup.strong" ] =  { fg="#fe0000",  bold = true },
    [ "@markup.italic" ] =  { fg="#875fff",  italic = true },
    [ "@markup.list"] =     { fg="#5f5fff",  bold = true },
    [ "@markup.raw" ] =  { fg="#5f5f87" },
    [ "@punctuation.special" ] =  { fg="#454545" },
    [ "@markup.quote" ] =  { fg="#5f5f87", bold = true },
    [ "@markup.link.label" ] =  { fg="#875fff", italic = true },


    mkdCode = { fg = "#00afff", bg = "none"},
    qfFileName = { fg = "#6c6c6c", bg = "none"},
    mkdnonlistitemblock = { fg = "#4c4c4c", bg = "none"},
    mkdbold = { fg = "#fe0000", bg = "none"},
    mkditalic = { fg = "#fe0000", bg = "none"},
    mkdcodedelimiter = { fg = "#fe0000", bg = "none"},
    mkdBoldItalic = { fg = "#fe0000", bg = "none"},
    htmlBoldItalic = { fg = "#4c4c4c", bg = "none"},
    NonText = { fg = "#fe3c3c", bg = "none"},


    [ "NvimTreeFolderIcon"       ] =  { fg="#b13738" },
    [ "NvimTreeFileIcon"         ] =  { fg="#fe0002" },
    [ "NvimTreeNormal"           ] =  { fg="#626262" },
    [ "NvimTreeExecFile"         ] =  { fg="#626262" },
    [ "NvimTreeImageFile"        ] =  { fg="#990c0a" },
    [ "NvimTreeEmptyFolderName"  ] =  { fg="#333333" },
    [ "NvimTreeSymlink"          ] =  { fg="#2B95B8" },
    [ "NvimTreeRootFolder"       ] =  { fg="#3c3c3c" },
    [ "NvimTreeGitDirty"         ] =  { fg="#cd0000" },
    [ "NvimTreeGitStaged"        ] =  { fg="#484b0a" },
    [ "NvimTreeGitNew"           ] =  { fg="#990c0a" },
    [ "NvimTreeIndentMarker"     ] =  { fg="#303030" },
    [ "NvimTreeVertSplit"        ] =  { fg="#4c4c4c" },
    [ "NvimTreeCursorLine"       ] =  { bg="#151515" },
    [ "NvimTreeSpecialFile"      ] =  { sp="#FF8700" },
    [ "NvimTreeFolderName"       ] =  { fg="#5f5f87", bold = true },
    [ "NvimTreeOpenedFolderName" ] =  { fg="#5f5f87", bold = true },
    [ "NvimTreeFileDirty"        ] =  { fg="#9c44ba", bold = true },
    [ "NvimTreeOpenedFile"       ] =  { fg="#fe0000", bold = true },

    qfError = { fg = "#fe0000", bg = "none"},

    [ "DiagnosticUnderlineError"] =  { fg="#fe0000", sp="#fff000", undercurl=true },
    [ "DiagnosticUnderlineWarn" ] =  { fg="none"   , sp="#555555", undercurl=false},
    [ "DiagnosticUnderlineInfo" ] =  { fg="none"   , sp="#5fd7ff", undercurl=false},
    [ "DiagnosticUnderlineHint" ] =  { sp="#5c5c5c"   , undercurl=false, nocombine=true },
    [ "DiagnosticVirtualTextError" ] =  { fg="#fe0000", bold = true },
    [ "DiagnosticVirtualTextWarn"  ] =  { fg="#bb4710", bold = true },
    [ "DiagnosticVirtualTextInfo"  ] =  { fg="#5f5f87" },
    [ "DiagnosticVirtualTextHint"  ] =  { fg="#4c4c4c", bold = true, italic = true },
    [ "DiagnosticHint"] =  { fg="#ff5f00" },
    [ "DiagnosticWarn"] =  { fg="#ff5f00" },
    [ "DiagnosticInfo"] =  { fg="#5F87FF", bold = true },

    TroublePreview = { fg = "none", bg = "#900707"},
    TroubleTextError = { fg = "#E44141", bg = "none"},
    TroubleTextWarning = { fg = "Orange", bg = "none"},
    TroubleTextInformation = { fg = "#5FD7Ff", bg = "none"},
    TroubleTextHint = { fg = "#ff5f00", bg = "none"},

    -- cmp / oil / etc
    [ "IndentBlanklineSpaceChar"] =  { fg="#fe0000", nocombine = true },
    [ "OilDir"] =  { fg="#5f5f88"    , bg="NONE"   , bold=true },
    [ "OilDirIcon"] =  { fg="#b23738", bg="NONE"   , bold=true },
    [ "Pmenu"                    ] =  { fg="#5c5c5c", bg="NONE"   ,  bold=true },
    [ "PmenuSel"                 ] =  { fg="NONE"   , bg="#36088d",  bold=true },
    [ "PmenuThumb"               ] =  { fg="NONE"   , bg="#2c2c2c",  bold=true },
    [ "PmenuSbar"                ] =  { fg="#FF55FF", bg="#333333",  bold=true },
    [ "Conceal"                  ] =  { fg="#00afff", bg="none"   ,  bold=true },
    [ "CmpBorder"                ] =  { fg="#0087ff", bg="none"   ,  bold=true },
    [ "CmpItemAbbrDeprecated"    ] =  { fg="#808080", bg="NONE"   ,  bold=true },
    [ "CmpItemAbbrMatch"         ] =  { fg="#875fff", bg="NONE"   ,  bold=true },
    [ "CmpItemAbbrMatchFuzzy"    ] =  { fg="#d75fff", bg="NONE"   ,  bold=true },
    [ "CmpItemKindVariable"      ] =  { fg="#fe4500", bg="NONE"   ,  bold=true },
    [ "CmpItemKindField"         ] =  { fg="#99329a", bg="NONE"   ,  bold=true },
    [ "CmpItemKindInterface"     ] =  { fg="#fe0000", bg="NONE"   ,  bold=true },
    [ "CmpItemKindFunction"      ] =  { fg="#0087ff", bg="NONE"   ,  bold=true },
    [ "CmpItemKindMethod"        ] =  { fg="#fe0000", bg="NONE"   ,  bold=true },
    [ "CmpItemKindKeyword"       ] =  { fg="#00d700", bg="none"   ,  bold=true },
    [ "CmpItemKindClass"         ] =  { fg="#ff5f00", bg="none"   ,  bold=true },
    [ "CmpItemKindProperty"      ] =  { fg="#5694D4", bg="NONE"   ,  bold=true },
    [ "CmpItemKindFolder"        ] =  { fg="#0087ff", bg="None"   ,  bold=true },
    [ "CmpItemKindFile"          ] =  { fg="#fe0000", bg="None"   ,  bold=true },
    [ "CmpItemKindUnit"          ] =  { fg="#ff5f00", bg="None"   ,  bold=true },
    [ "CmpItemKindEnum"          ] =  { fg="#d75fff", bg="None"   ,  bold=true },
    [ "CmpItemKindSnippet"       ] =  { fg="#64a200", bg="None"   ,  bold=true },
    [ "CmpItemKindText"          ] =  { fg="#5c5c5c", bg="NONE"   ,  bold=true },
    [ "CmpItemAbbr"              ] =  { fg="#555555" },
    [ "CmpItemKindConstant"      ] =  { fg="#d75fff", bg="None"   , bold = true },
    [ "Visual"                   ] =  { fg="#ff8100", bg="#2c2c2c", italic=true },



  }

  for group, hl in pairs(config.overrides) do
    if groups[group] then
      -- "link" should not mix with other configs (:h hi-link)
      groups[group].link = nil
    end

    groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
  end

  return groups
end

---@param config GruvboxConfig?
Gruvbox.setup = function(config)
  Gruvbox.config = vim.tbl_deep_extend("force", Gruvbox.config, config or {})
end

--- main load function
Gruvbox.load = function()
  if vim.version().minor < 8 then
    vim.notify_once("gruvbox.nvim: you must use neovim 0.8 or higher")
    return
  end

  -- reset colors
  if vim.g.colors_name then
    vim.cmd.hi("clear")
  end
  vim.g.colors_name = "gruvbox"
  vim.o.termguicolors = true

  local groups = get_groups()

  -- add highlights
  for group, settings in pairs(groups) do
    vim.api.nvim_set_hl(0, group, settings)
  end
end

return Gruvbox
